import type { GlossaryEntry } from './glossary';

/** Versión 1.4: la historia del magnate (fortunas, metas, dilemas, crónica, desafíos, rivales con memoria). */
export const GLOSSARY_V14: GlossaryEntry[] = [
  { id: 'ranking_fortunas', term: 'Lista de fortunas', category: 'Mercado y competencia',
    short: 'Las 100 personas más ricas de cada ciudad y un ranking global con las cuatro ciudades juntas.',
    purpose: 'Medir tu fortuna contra la del mundo del juego, no solo contra tu pasado.',
    how: 'Cada persona tiene un origen (tecnología, finanzas, inmuebles, industria, comercio, energía, salud o herencia) y su fortuna sigue al mercado de TU partida cada mes: la bolsa de su sector, el índice inmobiliario de su ciudad y las tasas, más su propia suerte y sus gastos. Los dueños de los grupos rivales están en la lista, y su fortuna incluye el grupo. Tu ciudad es la de tu residencia fiscal. Fuera del top 100 se estima tu puesto con la misma curva de la ciudad.',
    example: 'En Valdoria el puesto 100 arranca cerca de $4 M y el número 1 en unos $3,200 M. Si la bolsa tecnológica sube 20 % en un año, las fortunas tecnológicas suben más que las demás.',
    impact: 'Entrar en la lista, llegar al top 10 o al número 1 da logros, noticias y entradas en tu crónica. Siendo el número 1, quien está segundo puede lanzar una ofensiva.',
    tip: 'Mudar tu residencia a una ciudad con fortunas más chicas (Puerto Nuevo) te hace entrar antes en su lista, pero cambia tus impuestos y tu costo de vida.' },
  { id: 'metas_vida', term: 'Metas de vida', category: 'Acciones del juego',
    short: 'Objetivos que elegís vos (hasta 3 a la vez): tu casa, la cima de tu carrera, una fortuna limpia, superar a un rival…',
    purpose: 'Que tu partida tenga un rumbo propio, no solo acumular dinero.',
    how: 'Se cumplen por el estado real de la partida (no con un botón). Al cumplir una, sumás 3 de reputación, queda en tu crónica y podés elegir otra. Algunas pueden volverse imposibles (por ejemplo, «Una fortuna limpia» si cometiste un acto ilegal).',
    example: '«Independencia financiera» se cumple cuando tus ingresos pasivos cubren todos tus gastos fijos.',
    impact: 'Reputación, logros y una historia que se puede contar.' },
  { id: 'dilemas', term: 'Decisiones con plazo', category: 'Acciones del juego',
    short: 'Situaciones con 2 o 3 opciones que vencen en una fecha: un empleado que pide aumento, un amigo que busca inversores, un ascenso con mudanza…',
    purpose: 'Que tus decisiones tengan consecuencias que se sienten.',
    how: 'Cada opción dice qué cuesta y qué podés ganar. Todo pasa por el libro mayor, los empleados, la carrera y los rivales que ya existen. Si no decidís, se aplica la opción por defecto (que nunca cuesta dinero, pero tiene sus consecuencias). Algunas tienen un desenlace meses después. Pausan el tiempo si lo tenés activado en Ajustes.',
    example: 'Invertir $5,000 en la startup de un amigo se registra como gasto hoy; en uno o dos años puede volver multiplicado, en parte o nada.',
    impact: 'Dinero, reputación, contactos, estrés, moral de tus empleados y la actitud de los rivales.' },
  { id: 'cronica_magnate', term: 'Crónica del magnate', category: 'Acciones del juego',
    short: 'La historia de tu partida como línea de tiempo: etapas, logros, metas, decisiones, crisis y la competencia por la riqueza.',
    purpose: 'Recordar y contar lo que pasó en tu partida.',
    how: 'Se escribe sola. Cada 31 de diciembre agrega un resumen del año con tu patrimonio y tu puesto en la lista. Podés compartirla como texto.',
    example: '«2031 · Superaste a la Familia Duarte». «Tu 2034: patrimonio $1.2 M, creció 18 %».',
    impact: 'Ninguno en la economía: es tu historia.' },
  { id: 'desafios_semilla', term: 'Desafíos con semilla', category: 'Acciones del juego',
    short: 'Escenarios fijos: todos los que juegan un desafío empiezan en el mismo mundo (misma bolsa, mismos empleos, mismas crisis).',
    purpose: 'Comparar tu resultado con el de otras personas de forma justa, sin servidor.',
    how: 'Al cumplir el objetivo recibís un código (por ejemplo MILLON-3650-AB12CD) que incluye el resultado y una verificación contra errores de copia. Se puede comprobar en Más → Desafíos. Si se pasa el plazo, la partida sigue normalmente.',
    example: '«El primer millón»: empezás como autodidacta con $1,500; gana quien llega al millón en menos días.',
    impact: 'Rejugabilidad y maestría: el mismo mundo, otras decisiones.' },
  { id: 'rencor_rivales', term: 'Memoria de los rivales', category: 'Mercado y competencia',
    short: 'Los grupos rivales recuerdan lo que les hacés: si les ganás una compra, los superás en la lista o competís en sus sectores con varias empresas.',
    purpose: 'Que la competencia tenga caras y consecuencias.',
    how: 'Cada grupo tiene un rencor de 0 a 100 que baja solo con el tiempo. Cuanto más alto, más probable que abran competidores, cierren exclusividades con tus proveedores o tienten a tus empleados (hasta el doble). Pueden proponerte una tregua: dos años sin atacarte si no abrís empresas nuevas en un sector. Romperla tiene un costo alto.',
    example: 'Comprás la empresa que Grupo Altamira negociaba: su rencor sube 12 y aparece en su ficha.',
    impact: 'Más o menos ataques en tus sectores.' },
  { id: 'legado', term: 'Vida, legado y sucesión', category: 'Acciones del juego',
    short: 'Tu personaje envejece: puede formar una familia, jubilarse y pasarle la fortuna a un heredero.',
    purpose: 'Darle un final con sentido a las partidas largas y un nuevo comienzo que no borra lo construido.',
    how: 'Un año de juego dura 12 minutos a 1×. Desde los 50 la salud tiende a bajar; desde los 68 hay un riesgo de morir que crece con la edad y con mala salud. Desde los 60 podés jubilarte (tus negocios siguen) o pasar la posta: tu heredero (un hijo adulto o, si no hay, un sobrino) toma el control de todo con sus propias habilidades y sin empleo. Se paga el impuesto a la herencia de tu residencia: Valdoria 10 %, Isla Coral 0 %, Norvalia 25 %, Meridia 15 %, sobre lo que supera $500,000 a precios de hoy. Si no alcanza el efectivo, se paga en 24 cuotas.',
    formula: 'Impuesto = tasa × (patrimonio − mínimo exento).',
    example: 'Con $20 M en Norvalia: 25 % × ($20 M − $0.5 M) = $4.9 M. En Isla Coral: $0.',
    impact: 'Cambia quién dirige la fortuna, sus habilidades y su edad. La crónica guarda a cada generación.',
    tip: 'Donar a tu fundación o mudar la residencia antes de la sucesión cambia el impuesto (y tiene sus propios costos).' },
  { id: 'salida_bolsa', term: 'Salida a bolsa', category: 'Bolsa e inversiones',
    short: 'Una corporación rentable vende acciones nuevas al público y empieza a cotizar.',
    purpose: 'Conseguir mucho capital para crecer sin endeudarse, a cambio de compartir la propiedad.',
    how: 'Requisitos: corporación (S.A.) que tenés directamente, 24 meses de historia, ganancias en los últimos 12 meses, valoración mínima de $5 M a precios de hoy y al menos 70 % tuyo. Se ofrece entre 10 % y 30 % en acciones nuevas: el dinero entra a la caja de la empresa (menos 6 % de comisiones). El precio depende del ciclo: en un auge pagan hasta 25 % más que la valoración; en una recesión, 20 % menos.',
    example: 'Valoración $10 M en expansión (+12 %): ofrecer el 20 % trae ≈ $2.8 M a la caja.',
    impact: 'Reputación +8. Cada trimestre la prensa publica los resultados (las pérdidas restan reputación) y un rival puede comprar acciones e intentar quedarse con la empresa.',
    risks: 'La dilución es permanente. Una recompra de acciones cuesta más que el precio de mercado.' },
  { id: 'integracion_vertical', term: 'Proveedores propios', category: 'Empresas',
    short: 'Una empresa tuya le vende insumos o servicios a otra tuya con un precio interno.',
    purpose: 'Ahorrar costos y que tus empresas se potencien entre sí.',
    how: 'Minimercado → cafetería: 8 % menos en insumos. Consultora → cualquier empresa: 30 % menos de gastos administrativos. Fábrica de muebles → cafetería o minimercado: 25 % menos de mantenimiento. A cambio, el comprador le paga al proveedor un porcentaje de sus ventas (3 %, 1.5 % y 1 %), registrado como ingreso y gasto intragrupo.',
    example: 'Una cafetería que vende $40,000 por mes paga $1,200 a tu minimercado y ahorra el 8 % de sus insumos.',
    impact: 'Más margen para el comprador; ingresos para el proveedor. En un grupo, los pagos internos se eliminan al consolidar.' },
  { id: 'adquisicion_rival', term: 'Comprar un grupo rival', category: 'Mercado y competencia',
    short: 'Pagar el valor de un grupo rival más una prima de control para quedarte con él.',
    purpose: 'Sacarte de encima a un competidor para siempre.',
    how: 'Desde la etapa 8. Precio = caja del grupo + lo que compró, más 30 % de prima. Recibís una holding con esa caja; sus locales dejan de competir en tus mercados y el grupo nunca más te ataca. Su dueño cobra la venta y sigue en la lista de fortunas.',
    example: 'Un grupo que vale $20 M cuesta $26 M: tu patrimonio baja $6 M (la prima) y desaparece un rival.',
    impact: 'Menos competencia en tus sectores y reputación +6.' },
  { id: 'eras_economicas', term: 'Eras económicas', category: 'Economía',
    short: 'Cada 10–15 años cambia el contexto de fondo: auge digital, fiebre inmobiliaria, transición energética, austeridad…',
    purpose: 'Que el mundo cambie en las partidas largas: lo que rendía deja de rendir.',
    how: 'Una era es un evento económico largo con efectos moderados sobre la demanda de cada sector, la bolsa por sector, los inmuebles, los costos o el crédito. La primera llega a los 6 años de partida y se anuncia con anticipación en las noticias.',
    example: 'Durante el auge digital, el software vende 15 % más y las tecnológicas suben 6 % más por año.',
    impact: 'Cambia qué negocios e inversiones convienen durante una década.' },
  { id: 'rivalidad', term: 'Némesis, guerras de precios y coaliciones', category: 'Mercado y competencia',
    short: 'Cuando un grupo rival te odia de verdad, la competencia se vuelve personal.',
    purpose: 'Que crecer tenga consecuencias: los rivales reaccionan a vos.',
    how: 'Con rencor de 75 o más, un grupo se convierte en tu némesis: ataca más seguido hasta que lo vencés (lo comprás o tu fortuna duplica la de su dueño) o su rencor baja de 25. Con rencor de 55 o más puede iniciar una guerra de precios en un sector donde operás: baja 15 % los precios de sus locales (o abre un local de batalla) durante 4 a 8 meses, y le cuesta capital todos los meses. Cuando estás en el top 10 de tu ciudad o en la etapa 9, los dos grupos con más rencor pueden aliarse contra vos por 3 años. Un grupo que no te odia puede ofrecerte una alianza: no te ataca mientras dure.',
    example: 'Grupo Altamira inicia una guerra de precios en cafeterías: podés bajar tus precios, diferenciarte con calidad o aguantar.',
    impact: 'Más competidores, exclusividades y ofertas por tus empleados; logros por vencer a tu némesis y resistir una guerra de precios.' },
  { id: 'posicion_dominante', term: 'Posición dominante', category: 'Mercado y competencia',
    short: 'Cuando una empresa controla una parte muy grande de su mercado, la autoridad de competencia la vigila.',
    purpose: 'Que dominar un mercado traiga responsabilidades.',
    how: 'Si una empresa tuya vende cerca del 30 % o más de lo que compra su mercado, puede abrirse una investigación: comprometerte a bajar precios, pagar un acuerdo (2 % de las ventas anuales) o defenderte (abogados y 55 % de ganar; si perdés, 6 % de las ventas).',
    example: 'Tu minimercado vende $600,000 al año: el acuerdo cuesta $12,000; perder el juicio, $36,000.',
    impact: 'Margen, dinero y reputación.' },
  { id: 'equipo_directivo', term: 'Equipo directivo', category: 'Empresas',
    short: 'Un director general, uno de finanzas y uno de operaciones que coordinan tus empresas.',
    purpose: 'Que el tamaño sea un problema de gestión, no solo más ceros.',
    how: 'Hasta 4 empresas operando las coordinás vos. Desde la quinta, si no hay equipo directivo, tus gerentes pierden 8 puntos de habilidad por cada empresa extra (hasta 30): deciden peor, producen menos y la calidad baja. Con equipo, ganan 5 puntos. Cuesta $6,000 más $1,500 por empresa al mes (a precios de hoy).',
    example: 'Con 7 empresas y sin equipo, un gerente de habilidad 70 rinde como uno de 46. El equipo cuesta $16,500 por mes.',
    impact: 'Productividad, calidad y decisiones de los gerentes delegados.' },
  { id: 'bonos_corporativos', term: 'Bonos corporativos', category: 'Empresas',
    short: 'Deuda que tu corporación toma del mercado: paga intereses cada mes y devuelve todo al vencer.',
    purpose: 'Financiar un crecimiento grande sin entregar acciones.',
    how: 'Solo corporaciones (S.A.) con 24 meses de historia y ganancias. Se puede emitir hasta 3 veces el EBITDA anual menos la deuda que ya tiene, a 3, 5 o 10 años. La tasa es la de referencia más el diferencial de crédito más 2.5 puntos (1.5 si cotiza en bolsa), y sube si la empresa está muy endeudada o el plazo es largo. Comisión de colocación: 2 %.',
    formula: 'Cupón mensual = monto × tasa / 12. Al vencer: capital + último cupón.',
    example: '$2 M a 5 años al 9 %: $15,000 por mes de cupón y $2 M al final.',
    impact: 'Más caja hoy; un pago grande al vencer. Si no hay caja ese día, queda como deuda vencida.',
    risks: 'Refinanciar no está garantizado: planificá el vencimiento.' },
  { id: 'fusion_empresas', term: 'Fusión de empresas', category: 'Empresas',
    short: 'Una empresa tuya absorbe a otra tuya del mismo rubro: queda una sola.',
    purpose: 'Ahorrar costos fijos y unir equipos, clientes y equipos.',
    how: 'Las dos tienen que ser 100 % tuyas, del mismo rubro y jurisdicción, sin cotizar y sin impuestos pendientes. Todo lo de la absorbida (personal, equipos, inventario, deudas e inmuebles) pasa a la otra; su resultado del año tributa en la absorbente y sus pérdidas fiscales de años anteriores se pierden. Cuesta una integración: 3 % de las ventas anuales de la absorbida (mínimo $5,000).',
    example: 'Dos cafeterías con $8,000 de alquiler cada una: después de fusionarlas pagás un solo alquiler.',
    impact: 'Un alquiler y una administración menos; más capacidad en una sola empresa.' },
  { id: 'medallas_eficiencia', term: 'Medallas por eficiencia', category: 'Acciones del juego',
    short: 'Oro, plata o bronce según qué tan bien cumpliste un desafío, y logros que premian cómo crecés, no solo cuánto.',
    purpose: 'Maestría: hacerlo mejor la próxima vez.',
    how: 'Cada desafío tiene tres umbrales (en días o en patrimonio). Además hay logros de eficiencia: el millón en menos de 10 años, diez años sin atrasos, 100 empleados a la vez y $1 M de impuestos pagados sin evasión.',
    example: '«El primer millón» en 7 años: oro. En 11: plata.',
    impact: 'Logros y un código de resultado que incluye la medalla.' },
];
