import type { GlossaryEntry } from './glossary';

/** Bolsa, renta fija, fondos, Mogul Exchange y bienes raíces (Fase 3). */
export const GLOSSARY_INVEST: GlossaryEntry[] = [
  // ------------------------------------------------------------ Bolsa
  { id: 'accion', term: 'Acción', category: 'Bolsa e inversiones',
    short: 'Una pequeña parte de la propiedad de una empresa que cotiza en bolsa.',
    purpose: 'Participar en las ganancias y en el crecimiento de una empresa sin administrarla.',
    how: 'El precio cambia cada día hábil según el mercado, el sector, los resultados trimestrales y la oferta y demanda. Si la empresa reparte, cobrás dividendos. En tu balance se valúa al precio de mercado del día.',
    formula: 'Valor de tu tenencia = cantidad de acciones × precio actual',
    example: 'Comprás 50 acciones de Nébula a $84: invertís $4,200. Si suben a $92 valen $4,600 (ganancia no realizada de $400). Si las vendés, la ganancia pasa a ser realizada y tributa.',
    impact: 'Suma a tu patrimonio (a valor de mercado). Puede subir o bajar mucho: es dinero en riesgo.',
    risks: 'Caídas del mercado, malos resultados, quiebra de la empresa (podés perder casi todo).',
    mistakes: 'Invertir dinero que vas a necesitar pronto; concentrar todo en una sola empresa.',
    versus: 'Bono: prestás dinero a cambio de un interés fijo. Acción: sos dueño de una parte y tu retorno es incierto.',
  },
  { id: 'bpa', term: 'Beneficio por acción (BPA)', category: 'Bolsa e inversiones',
    short: 'La ganancia de la empresa dividida por la cantidad de acciones.',
    purpose: 'Comparar la rentabilidad de empresas de distinto tamaño.',
    formula: 'BPA = Beneficio neto anual ÷ acciones en circulación',
    example: 'Una empresa gana $12 millones y tiene 4 millones de acciones: BPA = $3.',
    impact: 'Cada trimestre se publica el BPA real; si supera lo esperado, la acción suele subir.',
    how: 'En el juego el BPA se actualiza con cada presentación trimestral: 3/4 del BPA anterior más el nuevo trimestre.',
  },
  { id: 'pe_ratio', term: 'Relación precio/beneficio (P/E)', category: 'Bolsa e inversiones',
    short: 'Cuántos años de ganancias actuales pagás al comprar una acción.',
    purpose: 'Saber si una acción está cara o barata frente a sus ganancias y a su sector.',
    formula: 'P/E = Precio ÷ BPA anual',
    example: 'Precio $60 y BPA $4 → P/E 15. Si el sector suele valer 18 veces, podría estar barata (o el mercado espera problemas).',
    impact: 'Un P/E alto implica expectativas de crecimiento: si no se cumplen, la caída puede ser fuerte.',
    how: 'El juego calcula un "P/E justo" por sector, ajustado por crecimiento, salud financiera y tasa de interés. El precio tiende lentamente hacia BPA × P/E justo.',
    risks: 'Con ganancias negativas el P/E no tiene sentido.',
  },
  { id: 'valor_justo', term: 'Valor justo (valor intrínseco)', category: 'Bolsa e inversiones',
    short: 'El precio que "debería" tener una acción según sus fundamentos.',
    purpose: 'Detectar acciones caras o baratas.',
    formula: 'Valor justo = BPA × P/E justo del sector (ajustado por crecimiento, salud y tasas)',
    example: 'BPA $2.50 × P/E justo 20 = $50. Si cotiza a $40, el precio tiende a subir hacia $50 con el tiempo… si nada cambia.',
    impact: 'En el juego el precio se acerca a su valor justo alrededor de 0.15 % de la diferencia por día (unos 10 % en 3 meses), pero el ruido diario y los eventos pueden alejarlo.',
    risks: 'Tu estimación del valor justo tiene error: depende de tu habilidad de Predicción bursátil.',
  },
  { id: 'prediccion_bursatil', term: 'Predicción bursátil', category: 'Bolsa e inversiones',
    short: 'Tu capacidad de estimar el valor de una acción y su rumbo probable.',
    purpose: 'Tomar mejores decisiones de compra y venta.',
    how: 'La estimación del valor justo tiene un margen de error que baja con tu habilidad (de ±35 % a un mínimo de ±6 %). Un asesor financiero contratado también lo reduce. El error es estable durante una semana.',
    formula: 'Error = 35 % × (1 − habilidad ÷ 120), mínimo 6 %',
    example: 'Con habilidad 20 el error es ±29 %; con habilidad 90, ±9 %. Aun con estimación perfecta, el precio futuro tiene ruido y eventos.',
    impact: 'Mejora con la práctica (analizar acciones, operar) y con cursos. Nunca llega al 100 %.',
    risks: 'Confiar demasiado en una estimación: siempre hay incertidumbre.',
  },
  { id: 'dividend_yield', term: 'Rendimiento por dividendo', category: 'Bolsa e inversiones',
    short: 'Cuánto te paga una acción en dividendos al año en relación con su precio.',
    purpose: 'Comparar acciones como fuente de ingresos pasivos.',
    formula: 'Rendimiento = dividendos anuales por acción ÷ precio',
    example: 'Telvaria paga $0.45 por trimestre ($1.80 al año) y cuesta $27: rendimiento 6.7 %.',
    impact: 'Los dividendos se cobran en la fecha ex-dividendo; el precio cae ese día en lo pagado. Se retiene el impuesto de tu jurisdicción.',
    risks: 'Un rendimiento muy alto puede anticipar un recorte.',
  },
  { id: 'orden_mercado', term: 'Orden de mercado', category: 'Bolsa e inversiones',
    short: 'Comprar o vender ya, al mejor precio disponible.',
    purpose: 'Operar de inmediato.',
    how: 'Se ejecuta al precio de cierre más la mitad del diferencial compra/venta y el impacto de tu orden. En fin de semana queda en cola para la apertura del lunes.',
    example: 'Precio $50, diferencial 0.2 %: comprás a ~$50.05 más comisión.',
    impact: 'Rapidez garantizada, precio no garantizado.',
    versus: 'Orden límite: precio garantizado, ejecución no garantizada.',
  },
  { id: 'orden_limite', term: 'Orden límite', category: 'Bolsa e inversiones',
    short: 'Comprar solo si el precio baja hasta X (o vender solo si sube hasta X).',
    purpose: 'Controlar el precio de ejecución.',
    how: 'Cada día hábil se compara con el mínimo y el máximo del día. Si el precio abre mejor que tu límite, se ejecuta a la apertura.',
    example: 'La acción está en $50 y ponés compra límite a $46. Si algún día toca $46, comprás a $46.',
    impact: 'Puede no ejecutarse nunca; vence en la fecha indicada.',
  },
  { id: 'stop_loss', term: 'Stop loss', category: 'Bolsa e inversiones',
    short: 'Vender automáticamente si el precio cae hasta un nivel, para limitar la pérdida.',
    purpose: 'Proteger una posición sin mirar el mercado todos los días.',
    how: 'Se activa cuando el mínimo del día toca el precio stop y se ejecuta con un pequeño deslizamiento. Si la acción abre muy por debajo (gap), vendés a la apertura.',
    example: 'Compraste a $50 y ponés stop en $44: si cae a $44 vendés y limitás la pérdida a ~12 %.',
    impact: 'Limita pérdidas grandes, pero una caída pasajera puede sacarte justo antes de un rebote.',
    risks: 'En caídas bruscas el precio de venta puede ser peor que el stop.',
  },
  { id: 'stop_limite', term: 'Stop-límite', category: 'Bolsa e inversiones',
    short: 'Un stop que, al activarse, se convierte en orden límite.',
    purpose: 'Evitar vender demasiado barato en una caída brusca.',
    example: 'Stop $44 y límite $43: si toca $44 queda una venta límite a $43; si el precio cae a $40 sin pasar por $43, no vendés.',
    impact: 'Más control de precio, pero puede quedar sin ejecutar.',
  },
  { id: 'take_profit', term: 'Toma de ganancias', category: 'Bolsa e inversiones',
    short: 'Vender automáticamente cuando el precio sube hasta tu objetivo.',
    purpose: 'Asegurar ganancias sin tener que vigilar el precio.',
    example: 'Compraste a $50 y ponés toma de ganancias en $60: si toca $60, vendés.',
    impact: 'Funciona como una venta límite por encima del precio actual.',
  },
  { id: 'trailing_stop', term: 'Stop dinámico (trailing stop)', category: 'Bolsa e inversiones',
    short: 'Un stop loss que sube solo a medida que la acción sube.',
    purpose: 'Dejar correr las ganancias y protegerlas si el precio se da vuelta.',
    formula: 'Stop = máximo alcanzado desde la orden × (1 − porcentaje elegido)',
    example: 'Con 10 %: si la acción sube de $50 a $70, el stop sube a $63. Si luego cae a $63, vendés.',
    impact: 'Nunca baja: solo sube con nuevos máximos.',
  },
  { id: 'oco', term: 'Orden OCO (una cancela la otra)', category: 'Bolsa e inversiones',
    short: 'Un stop loss y una toma de ganancias sobre las mismas acciones: cuando se ejecuta una, la otra se cancela.',
    purpose: 'Proteger una posición por arriba y por abajo a la vez.',
    example: '100 acciones compradas a $50: stop $45 y objetivo $60. Si llega primero a $60, vendés con ganancia y el stop desaparece.',
    impact: 'Evita vender dos veces las mismas acciones.',
  },
  { id: 'spread', term: 'Diferencial compra/venta', category: 'Bolsa e inversiones',
    short: 'La diferencia entre el precio al que podés comprar y el precio al que podés vender.',
    purpose: 'Es un costo oculto de cada operación.',
    how: 'En la bolsa del juego va de 0.08 % a 1 % según la volatilidad y el volumen de la acción. En Mogul Exchange es de 3 % a 5 % (activos poco líquidos).',
    example: 'Con 1 % de diferencial, comprar y vender enseguida te cuesta ~1 % más comisiones.',
    impact: 'Operar muy seguido multiplica este costo.',
  },
  { id: 'impacto_mercado', term: 'Impacto de mercado', category: 'Bolsa e inversiones',
    short: 'Cuánto mueve el precio tu propia orden.',
    purpose: 'Entender por qué comprar mucho de golpe sale más caro.',
    formula: 'Impacto ≈ 0.5 × volatilidad diaria × √(cantidad ÷ volumen diario promedio)',
    example: 'Comprar el 10 % del volumen diario de una acción volátil puede subir el precio 0.5 %–1 %.',
    impact: 'La mitad del impacto queda en el precio: tu compra lo sube, tu venta lo baja (oferta y demanda).',
  },
  { id: 'comision_corretaje', term: 'Comisión de inversión', category: 'Bolsa e inversiones',
    short: 'Lo que cobra el intermediario por cada operación.',
    purpose: 'Es un costo que reduce tu rentabilidad.',
    formula: 'Acciones: 0.2 % (mínimo $1, ajustado por inflación). Bonos: 0.1 %. Mogul: 0.5 %. Fondos: sin comisión de compra (salvo el REIT, 1 %).',
    example: 'Comprar $5,000 en acciones cuesta $10 de comisión.',
    impact: 'Se registra como gasto y reduce la ganancia de capital que tributa.',
  },
  { id: 'ganancia_no_realizada', term: 'Ganancia (o pérdida) no realizada', category: 'Bolsa e inversiones',
    short: 'Lo que ganarías o perderías si vendieras hoy.',
    purpose: 'Ver cuánto vale tu inversión sin venderla.',
    how: 'Tus inversiones se valúan a precio de mercado cada día (inmuebles, cada mes por tasación). La diferencia contra el costo aparece como "Revalorización no realizada", que NO paga impuestos.',
    formula: 'No realizada = valor de mercado − costo de compra',
    example: 'Compraste a $4,000; hoy vale $4,600: +$600 no realizados.',
    impact: 'Sube o baja tu patrimonio neto, pero no tu dinero disponible.',
    versus: 'Realizada: la que se concreta al vender; esa sí tributa.',
  },
  { id: 'costo_fifo', term: 'Costo FIFO', category: 'Bolsa e inversiones',
    short: 'Al vender, se considera que vendés primero lo que compraste primero.',
    purpose: 'Calcular la ganancia y el plazo de tenencia de cada venta.',
    example: 'Compraste 10 acciones a $40 y luego 10 a $60. Si vendés 10 a $70, tu costo es $40 (las primeras): ganancia $300.',
    impact: 'Determina si la ganancia es de corto o largo plazo, que en algunas jurisdicciones tributan distinto.',
  },
  { id: 'indice_bursatil', term: 'Índice bursátil', category: 'Bolsa e inversiones',
    short: 'Un número que resume la evolución de todas las acciones de la bolsa.',
    purpose: 'Medir cómo le va al mercado en general.',
    formula: 'Índice = capitalización total ÷ divisor (ajustado para que las salidas a bolsa y exclusiones no lo alteren)',
    example: 'El índice pasa de 1,000 a 1,080: el mercado subió 8 %.',
    impact: 'Si tu cartera rinde menos que el índice, un fondo índice habría sido mejor opción.',
  },
  { id: 'split', term: 'Split (división de acciones)', category: 'Bolsa e inversiones',
    short: 'La empresa divide cada acción en varias más baratas.',
    purpose: 'Hacer la acción más accesible cuando su precio es muy alto.',
    example: 'Tenés 10 acciones a $420; tras un split 2×1 tenés 20 a $210. Valor total: el mismo.',
    impact: 'No cambia el valor de tu inversión.',
  },
  { id: 'beta', term: 'Beta', category: 'Bolsa e inversiones',
    short: 'Cuánto se mueve una acción cuando se mueve el mercado.',
    purpose: 'Medir el riesgo "de mercado" de una acción o cartera.',
    example: 'Beta 1.5: si el índice cae 10 %, la acción tiende a caer 15 %. Beta 0.6: tiende a caer 6 %.',
    impact: 'Carteras con beta alta ganan más en auges y pierden más en recesiones.',
  },
  { id: 'volatilidad', term: 'Volatilidad', category: 'Bolsa e inversiones',
    short: 'Cuánto varía un precio de un período a otro.',
    purpose: 'Medir la incertidumbre de una inversión.',
    formula: 'Volatilidad anual ≈ desvío de los retornos diarios × √252',
    example: 'Volatilidad 30 %: en un año "típico" el precio puede terminar ±30 % de donde esperabas.',
    impact: 'Más volatilidad = más riesgo de tener que vender en un mal momento.',
  },
  { id: 'var', term: 'Valor en riesgo (VaR)', category: 'Bolsa e inversiones',
    short: 'La pérdida que no se debería superar en un período con 95 % de confianza.',
    purpose: 'Resumir el riesgo de tu cartera en dinero.',
    formula: 'VaR 95 % a 1 mes ≈ 1.65 × volatilidad mensual × valor de la cartera',
    example: 'Cartera de $20,000 con VaR de $2,100: en 19 de cada 20 meses no deberías perder más de eso.',
    impact: 'El 5 % restante puede ser mucho peor (crisis, pánicos).',
  },
  { id: 'drawdown', term: 'Caída máxima (drawdown)', category: 'Bolsa e inversiones',
    short: 'La mayor caída desde un máximo hasta un mínimo posterior.',
    purpose: 'Saber cuánto dolor aguantó (o aguantaría) una inversión.',
    example: 'Una acción sube a $80 y luego cae a $56: caída máxima de 30 %.',
    impact: 'Te dice cuánto tendrías que recuperar: tras −30 % hace falta +43 %.',
  },
  { id: 'media_movil', term: 'Media móvil (SMA/EMA)', category: 'Bolsa e inversiones',
    short: 'El promedio del precio de los últimos N días, que se desplaza cada día.',
    purpose: 'Suavizar el ruido y ver la tendencia.',
    formula: 'SMA = promedio simple de N cierres. EMA: promedio que pesa más los días recientes.',
    example: 'Si el precio cruza por encima de su media de 50 días, algunos lo leen como tendencia alcista.',
    impact: 'Es un indicador técnico: describe el pasado, no garantiza el futuro.',
  },
  { id: 'rsi', term: 'RSI (índice de fuerza relativa)', category: 'Bolsa e inversiones',
    short: 'Un indicador de 0 a 100 que compara subidas y bajadas recientes.',
    purpose: 'Detectar si una acción subió o bajó "demasiado rápido".',
    formula: 'RSI = 100 − 100 ÷ (1 + promedio de subidas ÷ promedio de bajadas), 14 días',
    example: 'RSI 78: subió fuerte (sobrecompra). RSI 25: cayó fuerte (sobreventa).',
    impact: 'En el juego el momento (tendencia) existe, así que el RSI da información… pero no certeza.',
  },
  { id: 'macd', term: 'MACD', category: 'Bolsa e inversiones',
    short: 'Diferencia entre una media móvil exponencial rápida (12) y una lenta (26), con su línea de señal (9).',
    purpose: 'Ver cambios de impulso en la tendencia.',
    formula: 'MACD = EMA12 − EMA26; señal = EMA9 del MACD',
    example: 'Cuando el MACD cruza por encima de su señal, el impulso se vuelve alcista.',
    impact: 'Indicador técnico: útil para contexto, no infalible.',
  },
  { id: 'bollinger', term: 'Bandas de Bollinger', category: 'Bolsa e inversiones',
    short: 'Una media de 20 días con bandas a ±2 desvíos.',
    purpose: 'Ver si el precio está en un extremo de su rango habitual.',
    example: 'Precio en la banda superior: está caro respecto de su rango reciente.',
    impact: 'Las bandas se ensanchan cuando sube la volatilidad.',
  },
  // ------------------------------------------------------------ Renta fija
  { id: 'bono', term: 'Bono', category: 'Bolsa e inversiones',
    short: 'Un préstamo que le hacés a un gobierno o empresa a cambio de intereses (cupones) y la devolución del capital al vencimiento.',
    purpose: 'Obtener ingresos más previsibles que con acciones.',
    how: 'Cada bono tiene nominal de $1,000, un cupón fijo semestral y una fecha de vencimiento. Su precio es el valor presente de los pagos que faltan, descontados al rendimiento que exige hoy el mercado.',
    formula: 'Precio = Σ pagos futuros ÷ (1 + rendimiento/2)^(2 × años hasta cada pago)',
    example: 'Bono de $1,000 al 5 % a 5 años: cobrás $25 cada seis meses y $1,000 al final. Si las tasas suben al 6 %, su precio cae a ~$957.',
    impact: 'Los cupones son renta ordinaria. Si vendés antes del vencimiento, la diferencia con lo que pagaste es ganancia o pérdida de capital.',
    risks: 'Riesgo de tasa (si suben las tasas, cae el precio) e impago del emisor.',
    versus: 'Depósito a plazo: no cambia de valor pero no se puede vender. Bono: se puede vender antes, a precio de mercado.',
  },
  { id: 'cupon', term: 'Cupón', category: 'Bolsa e inversiones',
    short: 'El interés periódico que paga un bono.',
    purpose: 'Es el ingreso que genera la renta fija.',
    formula: 'Cupón semestral = nominal × tasa de cupón ÷ 2',
    example: '10 bonos de $1,000 al 4 %: cobrás $200 cada seis meses.',
    impact: 'Se registra como "Cupones de bonos" y tributa como renta ordinaria.',
  },
  { id: 'rendimiento_vencimiento', term: 'Rendimiento al vencimiento (TIR)', category: 'Bolsa e inversiones',
    short: 'La tasa anual que ganarías comprando hoy y manteniendo el bono hasta que vence.',
    purpose: 'Comparar bonos con distinto precio y cupón.',
    how: 'En el juego: tasa de política + prima por plazo + diferencial de crédito del emisor (mayor si es riesgoso o si la economía está en crisis).',
    example: 'Un bono con cupón 3 % que cotiza a $920 puede rendir 5 % al vencimiento.',
    impact: 'Cuanto mayor el rendimiento, mayor el riesgo que el mercado percibe (o mayores las tasas).',
  },
  { id: 'duracion', term: 'Duración', category: 'Bolsa e inversiones',
    short: 'Cuánto cae el precio de un bono si el rendimiento sube 1 punto.',
    purpose: 'Medir el riesgo de tasa de interés.',
    example: 'Duración 7: si las tasas suben 1 pp, el bono cae ~7 %.',
    impact: 'Los bonos largos tienen más duración: ganan más si bajan las tasas y pierden más si suben.',
  },
  { id: 'calificacion', term: 'Calificación crediticia', category: 'Bolsa e inversiones',
    short: 'Una nota (AAA, AA, A, BBB, BB, B, CCC, D) sobre el riesgo de que un emisor no pague.',
    purpose: 'Comparar el riesgo de impago.',
    how: 'Para empresas se calcula con su salud financiera y su endeudamiento; cambia con sus resultados.',
    example: 'AAA: casi sin riesgo. BB o menos: "alto rendimiento", con riesgo real de impago.',
    impact: 'Menor calificación = mayor rendimiento exigido = precio más bajo.',
  },
  { id: 'impago', term: 'Impago de un bono', category: 'Bolsa e inversiones',
    short: 'El emisor deja de pagar cupones y capital.',
    purpose: 'Es el principal riesgo de la renta fija de empresas.',
    how: 'Si la empresa emisora quiebra, sus bonos entran en impago y a los 90 días se liquidan pagando ~40 % del nominal. Un gobierno riesgoso puede reestructurar en recesiones.',
    example: 'Tenías 5 bonos ($5,000 nominales) de una empresa que quebró: recuperás ~$2,000.',
    impact: 'Pérdida de capital realizada.',
  },
  { id: 'fondo_inversion', term: 'Fondo de inversión', category: 'Bolsa e inversiones',
    short: 'Un vehículo que junta el dinero de muchos inversores y lo invierte por ellos.',
    purpose: 'Diversificar con poco dinero y sin elegir acción por acción.',
    how: 'Comprás "participaciones" al valor liquidativo del día. El valor se mueve con lo que tiene el fondo, menos una comisión anual que se descuenta a diario. Algunos reparten rentas cada trimestre.',
    formula: 'Participaciones = monto invertido ÷ valor liquidativo',
    example: 'Invertís $1,000 en el Fondo Índice con VL $100: recibís 10 participaciones.',
    impact: 'Se valúa a mercado en tu balance.',
    risks: 'Depende del fondo: un fondo sectorial es mucho más riesgoso que uno monetario.',
  },
  { id: 'valor_liquidativo', term: 'Valor liquidativo (VL)', category: 'Bolsa e inversiones',
    short: 'El valor de una participación de un fondo.',
    purpose: 'Es el precio al que suscribís y rescatás.',
    formula: 'VL = valor de los activos del fondo ÷ participaciones',
    example: 'VL $104.20: tus 10 participaciones valen $1,042.',
    impact: 'Cae el día que el fondo reparte rentas (lo repartido sale del fondo).',
  },
  { id: 'reit', term: 'Fondo inmobiliario (REIT)', category: 'Bolsa e inversiones',
    short: 'Un fondo que invierte en inmuebles alquilados y reparte los alquileres.',
    purpose: 'Invertir en inmuebles sin comprar uno entero.',
    example: 'Con $2,000 recibís una parte de los alquileres de muchos edificios cada trimestre.',
    impact: 'Su valor sigue a los precios inmobiliarios; reparte ~5 % anual antes de comisiones.',
  },
  // ------------------------------------------------------------ Mogul
  { id: 'mogul_exchange', term: 'Mogul Exchange', category: 'Bolsa e inversiones',
    short: 'Mercado de participaciones fraccionadas en activos privados: empresas, edificios y regalías.',
    purpose: 'Invertir en activos que normalmente solo compran los grandes inversores.',
    how: 'Cada activo tiene 10,000 participaciones. Su valor se recalcula a fin de mes: empresas con la misma valoración que usás para las tuyas, edificios por tasación y regalías por valor presente. Reparten rentas mensuales.',
    example: 'Comprás 100 participaciones de un edificio que vale $3 millones: tenés el 1 % ($30,000) y cobrás el 1 % de sus alquileres netos.',
    impact: 'Rentas: dividendos (empresas) o alquileres (edificios y regalías). Revalorización no realizada mensual.',
    risks: 'Poca liquidez (diferencial 3 %–5 %), riesgo de quiebra de la empresa, vacancia, fin de las regalías.',
  },
  { id: 'participacion_fraccionada', term: 'Participación fraccionada', category: 'Bolsa e inversiones',
    short: 'Ser dueño de una fracción de un activo junto con otros inversores.',
    purpose: 'Acceder a activos grandes con poco capital.',
    example: 'Con 0.5 % de una empresa recibís el 0.5 % de lo que reparte.',
    impact: 'No administrás el activo: dependés de su gestión.',
  },
  { id: 'regalias', term: 'Regalías', category: 'Bolsa e inversiones',
    short: 'Derecho a cobrar un porcentaje de los ingresos de una obra, patente o producción.',
    purpose: 'Generar flujo sin operar el negocio.',
    formula: 'Valor = Σ regalías futuras esperadas ÷ (1 + tasa)^n',
    example: 'Un catálogo musical paga $9,000 por mes, que decae 5 % por año durante 15 años.',
    impact: 'El valor tiende a cero hacia el final de su vida: parte de lo que cobrás es devolución de capital.',
  },
  // ------------------------------------------------------------ Bienes raíces
  { id: 'inmueble', term: 'Inmueble', category: 'Bienes raíces',
    short: 'Una vivienda, local, oficina o terreno.',
    purpose: 'Generar alquileres, valorizarse o usarlo (vivir o instalar una empresa).',
    how: 'Tasación = m² × precio de la zona × índice de la zona × categoría × estado. El índice de cada zona se mueve cada mes con el ciclo económico, las tasas, la inflación y los eventos. Los tuyos se valúan por tasación; los de tus empresas, al costo menos depreciación.',
    example: 'Departamento de 60 m² en Barrio Norte ($2,100/m², categoría 3, buen estado) ≈ $125,000.',
    impact: 'Suma a tu patrimonio. Genera alquileres y gastos: mantenimiento, impuesto inmobiliario, administración, reparaciones.',
    risks: 'Vacancia, inquilinos morosos, caída de precios, vicios ocultos, tasas en suba (hipotecas variables).',
  },
  { id: 'tasacion', term: 'Tasación', category: 'Bienes raíces',
    short: 'El valor de mercado estimado de un inmueble.',
    purpose: 'Saber cuánto vale, cuánto prestan los bancos y cuánto impuesto pagás.',
    formula: 'Tasación = m² × precio base × índice zona × (0.8 + 0.1 × categoría) × (0.75 + estado ÷ 400)',
    example: 'Si el índice de la zona sube 5 % en un año, la tasación sube 5 % (si el estado no empeoró).',
    impact: 'Se actualiza cada mes. El impuesto inmobiliario se calcula sobre ella.',
  },
  { id: 'alquiler', term: 'Alquiler', category: 'Bienes raíces',
    short: 'El pago mensual de un inquilino por usar tu inmueble.',
    purpose: 'Ingreso pasivo recurrente.',
    how: 'Publicás el alquiler que pedís; cada semana hay una probabilidad de conseguir inquilino que baja si pedís más que el mercado, si el estado es malo o si hay mucha vacancia. Los contratos son de 12 meses (viviendas) o 24 (locales y oficinas). Cada mes el inquilino puede no pagar; con 2 meses impagos empieza un desalojo.',
    example: 'Alquiler de mercado $1,200: pedir $1,400 puede demorar meses; pedir $1,150 se alquila rápido.',
    impact: 'Tributa como renta ordinaria (menos gastos, intereses y depreciación según tu jurisdicción).',
  },
  { id: 'vacancia', term: 'Vacancia', category: 'Bienes raíces',
    short: 'El tiempo o porcentaje de inmuebles sin inquilino.',
    purpose: 'Es el mayor enemigo de la rentabilidad inmobiliaria.',
    example: 'Un mes vacío por año reduce el ingreso anual ~8 %.',
    impact: 'Sube en recesiones y con eventos de corrección inmobiliaria.',
  },
  { id: 'gastos_inmueble', term: 'Gastos de un inmueble', category: 'Bienes raíces',
    short: 'Mantenimiento, reparaciones, administración y seguros de un inmueble.',
    purpose: 'Calcular la rentabilidad real.',
    formula: 'Mantenimiento mensual ≈ 0.1 % del valor del edificio (×1.5 si está en mal estado) + reparaciones aleatorias',
    example: 'Edificio de $100,000: ~$100/mes de mantenimiento.',
    impact: 'Se pagan aunque el inmueble esté vacío.',
  },
  { id: 'impuesto_inmobiliario', term: 'Impuesto inmobiliario', category: 'Bienes raíces',
    short: 'Impuesto anual sobre el valor de tus inmuebles, que se paga trimestralmente.',
    purpose: 'Es un costo fijo de ser propietario.',
    formula: 'Impuesto trimestral = tasación × tasa de la jurisdicción ÷ 4',
    example: 'Inmueble de $200,000 en Valdoria (1 %): $500 por trimestre. En Meridia (1.8 %): $900.',
    impact: 'Vence en marzo, junio, septiembre y diciembre.',
  },
  { id: 'hipoteca', term: 'Hipoteca', category: 'Bienes raíces',
    short: 'Un préstamo largo para comprar un inmueble, garantizado con ese inmueble.',
    purpose: 'Comprar un inmueble sin tener todo el dinero.',
    how: 'El banco financia hasta un porcentaje del precio (LTV). Cuota fija (sistema francés). Tasa fija o variable (se ajusta cada año con la tasa de política). Con 3 cuotas impagas el banco ejecuta el inmueble.',
    formula: 'Cuota = P × r ÷ (1 − (1 + r)^−n), con r = tasa anual ÷ 12 y n = meses',
    example: '$160,000 a 20 años al 7 %: cuota ≈ $1,240. Pagarías ~$137,600 de intereses en total.',
    impact: 'Aparece como pasivo. Los intereses son gasto (deducibles en alquileres según la jurisdicción).',
    risks: 'Apalancamiento: si el inmueble baja 20 % y financiaste el 80 %, perdiste tu anticipo.',
  },
  { id: 'ltv', term: 'LTV (préstamo / valor)', category: 'Bienes raíces',
    short: 'Qué porcentaje del precio te financia el banco.',
    purpose: 'Define cuánto anticipo necesitás y cuánto riesgo tomás.',
    formula: 'LTV = monto de la hipoteca ÷ precio',
    example: 'Precio $200,000 con hipoteca de $150,000: LTV 75 %, anticipo $50,000 + gastos.',
    impact: 'Más LTV = más rentabilidad sobre tu dinero si sube, y más pérdida si baja.',
  },
  { id: 'tasa_variable', term: 'Tasa fija vs. variable', category: 'Bienes raíces',
    short: 'Fija: la cuota no cambia. Variable: se ajusta cada año con la tasa del banco central.',
    purpose: 'Elegir entre certeza y costo inicial.',
    example: 'Variable empieza más barata, pero si la tasa de política sube 2 pp, tu cuota puede subir 15 %–20 %.',
    impact: 'La variable te expone a subas de tasas; la fija cuesta más al principio.',
  },
  { id: 'ejecucion_hipotecaria', term: 'Ejecución hipotecaria (embargo)', category: 'Bienes raíces',
    short: 'El banco remata el inmueble si dejás de pagar la hipoteca.',
    purpose: 'Es la garantía del banco.',
    how: 'Con 3 cuotas impagas, el banco vende al 75 % de la tasación y cobra 5 % de gastos. Si sobra, te lo devuelve. Si falta: con recurso seguís debiendo; sin recurso (Isla Coral) el banco asume la diferencia.',
    example: 'Tasación $200,000, deuda $170,000: remate $150,000 − $7,500 de gastos = $142,500; con recurso seguís debiendo $27,500.',
    impact: 'Pérdida grande, impago en tu historial crediticio y más estrés.',
  },
  { id: 'recurso_hipotecario', term: 'Hipoteca con o sin recurso', category: 'Bienes raíces',
    short: 'Con recurso: si el remate no cubre la deuda, seguís debiendo. Sin recurso: la deuda termina con el inmueble.',
    purpose: 'Entender cuánto podés perder como máximo.',
    example: 'Valdoria, Norvalia y Meridia: con recurso. Isla Coral: sin recurso.',
    impact: 'Cambia el peor escenario de una inversión apalancada.',
  },
  { id: 'cap_rate', term: 'Tasa de capitalización (cap rate)', category: 'Bienes raíces',
    short: 'Rentabilidad neta anual de un inmueble sobre su valor, sin considerar la hipoteca.',
    purpose: 'Comparar inmuebles entre sí.',
    formula: 'Cap rate = ingreso neto operativo anual ÷ valor',
    example: 'Alquiler $14,400/año − gastos $3,400 = $11,000 sobre $200,000: 5.5 %.',
    impact: 'Si el cap rate es menor que la tasa de la hipoteca, endeudarte reduce tu rentabilidad.',
  },
  { id: 'cash_on_cash', term: 'Rentabilidad sobre lo invertido (cash-on-cash)', category: 'Bienes raíces',
    short: 'Cuánto te rinde por año el dinero que pusiste de tu bolsillo.',
    purpose: 'Medir el efecto de la hipoteca.',
    formula: '(Ingreso neto operativo − cuotas de hipoteca) ÷ (anticipo + gastos de compra)',
    example: '$11,000 − $9,000 de cuotas = $2,000 sobre $60,000 invertidos: 3.3 %.',
    impact: 'No incluye la revalorización del inmueble ni la amortización de la deuda.',
  },
  { id: 'impuesto_transferencia', term: 'Gastos de escritura e impuesto de transferencia', category: 'Bienes raíces',
    short: 'Costos que pagás al comprar: impuesto de transferencia de la jurisdicción + escribanía (1 %).',
    purpose: 'Son parte del costo real de comprar.',
    example: 'Comprar por $200,000 en Valdoria cuesta $8,000 extra (3 % + 1 %). En Isla Coral, $16,000 (7 % + 1 %).',
    impact: 'Se registran como gasto: tu patrimonio baja el día de la compra.',
  },
  { id: 'vicio_oculto', term: 'Vicio oculto', category: 'Bienes raíces',
    short: 'Un defecto no visible del inmueble (humedad, estructura) que aparece después de comprar.',
    purpose: 'Es un riesgo de comprar sin inspección.',
    how: 'Alrededor de 1 de cada 7 inmuebles lo tiene. Una inspección ($400) lo revela; un abogado contratado además negocia que el vendedor lo pague.',
    example: 'Reparación sorpresa de $6,000 al tercer mes.',
    impact: 'Gasto no previsto.',
  },
  { id: 'desalojo', term: 'Desalojo', category: 'Bienes raíces',
    short: 'Proceso judicial para recuperar un inmueble de un inquilino que no paga.',
    purpose: 'Recuperar el inmueble para alquilarlo a otro.',
    example: 'Sin abogado: ~90 días y $1,500. Con un buen abogado: 30–60 días y menos costo.',
    impact: 'Meses sin cobrar alquiler.',
  },
];
