import { GLOSSARY_BUSINESS } from './glossaryBusiness';
import { GLOSSARY_INVEST } from './glossaryInvest';
import { GLOSSARY_WORLD } from './glossaryWorld';
import { GLOSSARY_ACTIONS3 } from './glossaryActions3';
import { GLOSSARY_V11 } from './glossaryV11';
import { GLOSSARY_V12 } from './glossaryV12';
import { GLOSSARY_V14 } from './glossaryV14';
/**
 * Glosario financiero y ayuda contextual.
 * Cada entrada sigue la estructura pedida: definición sencilla, para qué sirve,
 * cómo se calcula, ejemplo numérico, cómo te afecta, riesgos, errores comunes,
 * diferencia con conceptos parecidos y consejo contextual.
 */
export interface GlossaryEntry {
  id: string;
  term: string;
  category: 'Básicos' | 'Estados financieros' | 'Crédito y deuda' | 'Ahorro e inversión' | 'Impuestos' | 'Empleo' | 'Bienestar' | 'Empresas' | 'Acciones del juego'
    | 'Bolsa e inversiones' | 'Bienes raíces' | 'Economía' | 'Grupos empresariales' | 'Profesionales' | 'Sistema legal' | 'Estilo de vida' | 'Mercado y competencia';
  short: string;
  purpose: string;
  /** Cómo funciona (mecánica en el juego). */
  how?: string;
  formula?: string;
  example: string;
  impact: string;
  risks?: string;
  mistakes?: string;
  versus?: string;
  tip?: string;
}

const BASE_GLOSSARY: GlossaryEntry[] = [
  // BÁSICOS
  {
    id: 'patrimonio_neto', term: 'Patrimonio neto', category: 'Básicos',
    short: 'Es el valor de todo lo que tenés (activos) menos todo lo que debés (pasivos).',
    purpose: 'Es la medida real de tu riqueza. Es el número que el juego usa para tu progreso.',
    formula: 'Patrimonio neto = Activos − Pasivos',
    example: 'Tenés $3,000 en el banco y $1,000 en un depósito (activos = $4,000). Debés $500 de tarjeta (pasivo). Patrimonio neto = $3,500.',
    impact: 'Sube cuando ganás más de lo que gastás o cuando tus activos se valorizan. Pedir un préstamo NO lo aumenta: suma dinero y deuda por igual.',
    mistakes: 'Confundirlo con el dinero disponible. Podés tener patrimonio alto y quedarte sin efectivo si todo está inmovilizado.',
    versus: 'Liquidez: cuánto podés usar YA. Patrimonio: cuánto vale todo, se pueda usar o no.',
    tip: 'Mirá su evolución mes a mes en Informes → Patrimonio, no el número de un día.',
  },
  {
    id: 'liquidez', term: 'Liquidez', category: 'Básicos',
    short: 'Es el dinero y los recursos que podés usar rápidamente para pagar obligaciones.',
    purpose: 'Determina si podés pagar tus cuentas este mes. Sin liquidez aparecen atrasos aunque seas "rico" en papel.',
    formula: 'Liquidez disponible = Efectivo + Cuenta corriente + Cuenta de ahorro',
    example: 'Con $1,200 líquidos y gastos de $890/mes, tenés liquidez para 1.3 meses si no cobrás nada.',
    impact: 'Si llega a cero, los pagos se cargan a la tarjeta y después quedan como atrasos con recargo.',
    risks: 'Invertir todo en depósitos a plazo reduce la liquidez: cancelarlos antes cuesta intereses y comisión.',
    mistakes: 'Creer que tener muchos activos garantiza liquidez.',
    versus: 'Solvencia: capacidad de pagar TODAS tus deudas a largo plazo. Podés ser solvente e ilíquido.',
  },
  {
    id: 'flujo_caja', term: 'Flujo de caja', category: 'Estados financieros',
    short: 'Representa el dinero que entra y sale realmente durante un período.',
    purpose: 'Muestra si tus cuentas se llenan o se vacían, sin importar lo que "ganaste" en papel.',
    formula: 'Flujo neto = Cobros − Pagos (en efectivo)',
    example: 'Cobrás $976 netos y pagás $890 de gastos: flujo operativo +$86. Si ese mes además pagás $300 de tarjeta, el flujo total es −$214.',
    impact: 'Un flujo negativo sostenido agota tu liquidez.',
    mistakes: 'Pensar que comprar con tarjeta no afecta el flujo: lo afecta cuando pagás la tarjeta.',
    versus: 'Beneficio (resultado): se registra cuando el ingreso o el gasto ocurre, aunque no se haya pagado todavía.',
    tip: 'El estado de flujo de caja separa operaciones, inversión y financiamiento. Un buen flujo operativo es la base de todo.',
  },
  {
    id: 'ingresos_vs_beneficio', term: 'Ingresos vs. beneficio', category: 'Estados financieros',
    short: 'Ingreso es lo que entra antes de restar nada; beneficio es lo que queda después de restar gastos.',
    purpose: 'Evita que te sientas rico por ingresar mucho cuando en realidad gastás casi todo.',
    formula: 'Beneficio = Ingresos − Gastos',
    example: 'Una empresa factura $100,000 (ingresos) y gasta $95,000: su beneficio es $5,000.',
    impact: 'Tu patrimonio crece con el beneficio, no con los ingresos.',
    mistakes: 'Comparar negocios por facturación en lugar de beneficio.',
  },
  {
    id: 'partida_doble', term: 'Partida doble', category: 'Estados financieros',
    short: 'Cada operación se registra en al menos dos cuentas: lo que entra en una sale de otra.',
    purpose: 'Garantiza que el dinero nunca aparezca ni desaparezca sin explicación. Todo el juego funciona así.',
    formula: 'En cada asiento: Suma del Debe = Suma del Haber',
    example: 'Pagar $450 de alquiler: Debe Vivienda $450 / Haber Cuenta corriente $450.',
    impact: 'Podés auditar cualquier cifra en Informes → Libro mayor.',
  },
  {
    id: 'activo', term: 'Activo', category: 'Estados financieros',
    short: 'Todo lo que tenés y tiene valor: dinero, depósitos, fondo de jubilación, (más adelante) acciones, propiedades y empresas.',
    purpose: 'Es la primera mitad del patrimonio neto.',
    example: 'Cuenta corriente $1,500 + depósito $2,000 + jubilación $300 = activos $3,800.',
    impact: 'No todos los activos son líquidos: el fondo de jubilación no se puede usar para pagar el alquiler.',
    versus: 'Pasivo: lo que debés.',
  },
  {
    id: 'pasivo', term: 'Pasivo', category: 'Estados financieros',
    short: 'Todo lo que debés: tarjeta, préstamos, impuestos por pagar, atrasos.',
    purpose: 'Es la segunda mitad del patrimonio neto.',
    example: 'Tarjeta $400 + préstamo $2,600 = pasivos $3,000.',
    impact: 'Los pasivos suelen generar intereses que reducen tu resultado cada mes.',
  },
  {
    id: 'estado_resultados', term: 'Estado de resultados', category: 'Estados financieros',
    short: 'Informe que muestra ingresos, gastos e impuestos de un período y cuánto quedó.',
    purpose: 'Responde "¿gané o perdí este mes/año?".',
    formula: 'Ingresos brutos − Gastos = Resultado antes de impuestos; − Impuestos = Resultado neto',
    example: 'Ingresos $1,100; gastos de vida $890; impuestos y seguridad social $120 → resultado neto $90.',
    impact: 'El resultado neto es exactamente lo que cambió tu patrimonio en el período.',
    versus: 'El flujo de caja mide movimientos de dinero; el estado de resultados mide ganancias y pérdidas.',
  },
  {
    id: 'balance_general', term: 'Balance general', category: 'Estados financieros',
    short: 'Foto de lo que tenés y lo que debés en un momento dado.',
    purpose: 'Muestra tu estructura financiera: cuánto es líquido, cuánto invertido y cuánto debido.',
    formula: 'Activo = Pasivo + Patrimonio',
    example: 'Activos $5,000 = Pasivos $1,000 + Patrimonio $4,000.',
    impact: 'Si los pasivos crecen más rápido que los activos, tu patrimonio cae.',
  },
  {
    id: 'capital_trabajo', term: 'Capital de trabajo', category: 'Estados financieros',
    short: 'Recursos de corto plazo disponibles después de cubrir las deudas de corto plazo.',
    purpose: 'Mide el colchón operativo para funcionar sin quedarse sin dinero.',
    formula: 'Capital de trabajo = Activo corriente − Pasivo corriente',
    example: 'Liquidez $3,000 − (tarjeta $500 + cuotas del año $1,200) = $1,300.',
    impact: 'En tus empresas, el inventario y las cuentas por cobrar consumen capital de trabajo.',
    versus: 'Liquidez corriente = Activo corriente ÷ Pasivo corriente (un ratio, no un monto).',
  },
  {
    id: 'margen_bruto', term: 'Margen bruto', category: 'Estados financieros',
    short: 'Porcentaje de cada venta que queda después de pagar el costo directo del producto.',
    purpose: 'Indica cuánto margen tiene un negocio para cubrir sueldos, alquiler y beneficio.',
    formula: 'Margen bruto = (Ventas − Costo de ventas) ÷ Ventas',
    example: 'Vendés a $10 algo que cuesta $6: margen bruto 40 %.',
    impact: 'Cada empresa lo muestra en su estado de resultados.',
  },
  {
    id: 'beneficio_operativo', term: 'Beneficio operativo', category: 'Estados financieros',
    short: 'Beneficio de la actividad principal antes de intereses e impuestos.',
    purpose: 'Permite comparar negocios sin que influya cómo se financian.',
    formula: 'Beneficio operativo = Beneficio bruto − Gastos operativos',
    example: 'Beneficio bruto $40,000 − sueldos y alquiler $30,000 = $10,000.',
    impact: 'Aparece en el estado de resultados de cada empresa.',
    versus: 'Beneficio neto: después de intereses e impuestos.',
  },
  {
    id: 'flujo_caja_libre', term: 'Flujo de caja libre', category: 'Estados financieros',
    short: 'Dinero que queda tras las operaciones y las inversiones necesarias para mantener la actividad.',
    purpose: 'Es lo que realmente podés usar para pagar deudas, repartir o crecer.',
    formula: 'FCL = Flujo operativo − Inversiones en activos productivos',
    example: 'Flujo operativo $12,000 − compra de maquinaria $5,000 = $7,000.',
    impact: 'En finanzas personales coincide con el flujo operativo; en empresas se restan las compras de equipos.',
  },
  // CRÉDITO Y DEUDA
  {
    id: 'interes', term: 'Interés', category: 'Crédito y deuda',
    short: 'El precio de usar dinero ajeno (si debés) o el pago por prestar el tuyo (si ahorrás).',
    purpose: 'Determina cuánto cuesta una deuda y cuánto rinde un ahorro.',
    formula: 'Interés mensual ≈ Saldo × Tasa anual ÷ 12',
    example: '$1,000 de tarjeta al 27 % anual ≈ $22.50 de interés por mes.',
    impact: 'Los intereses de deudas son gastos; los de ahorros son ingresos (y pagan impuesto).',
    mistakes: 'Mirar solo la cuota y no el costo total de intereses.',
  },
  {
    id: 'interes_compuesto', term: 'Interés compuesto', category: 'Ahorro e inversión',
    short: 'Ganar intereses sobre intereses ya ganados.',
    purpose: 'Es el motor del crecimiento del ahorro a largo plazo (y de las deudas que no pagás).',
    formula: 'Valor final = Capital × (1 + tasa)^períodos',
    example: '$1,000 al 5 % anual: año 1 = $1,050; año 2 = $1,102.50; en 20 años ≈ $2,653.',
    impact: 'La cuenta de ahorro capitaliza mensualmente: los intereses se suman al saldo y generan más intereses.',
    risks: 'Funciona igual en contra: una deuda de tarjeta sin pagar crece de forma compuesta.',
  },
  {
    id: 'apalancamiento', term: 'Apalancamiento', category: 'Crédito y deuda',
    short: 'Usar deuda para invertir más de lo que tenés.',
    purpose: 'Multiplica resultados: si la inversión rinde más que el costo de la deuda, ganás más; si no, perdés más.',
    formula: 'Apalancamiento = Activos ÷ Patrimonio',
    example: 'Con $10,000 propios y $30,000 prestados invertís $40,000: apalancamiento 4×.',
    impact: 'Aparece al financiar empresas con préstamos; en bienes raíces llega en la Fase 3.',
    risks: 'Pequeñas pérdidas se convierten en grandes pérdidas del capital propio.',
  },
  {
    id: 'solvencia', term: 'Solvencia', category: 'Crédito y deuda',
    short: 'Capacidad de pagar todas tus deudas con tus activos.',
    purpose: 'Indica si tu situación es sostenible a largo plazo.',
    formula: 'Ratio deuda/activos = Pasivos ÷ Activos',
    example: 'Deudas $20,000 y activos $80,000: 25 % (solvente).',
    impact: 'Una de las condiciones de progreso es mantener deuda/activos bajo 50 %.',
    versus: 'Liquidez: pagar lo inmediato. Solvencia: pagar todo.',
  },
  {
    id: 'tarjeta_credito', term: 'Tarjeta de crédito', category: 'Crédito y deuda',
    short: 'Línea de crédito para compras que se paga con un resumen mensual.',
    purpose: 'Da flexibilidad y construye historial crediticio si se usa bien.',
    formula: 'Corte el día 25 · vencimiento 20 días después · interés = saldo promedio diario × tasa ÷ 365 × días',
    example: 'Gastás $300; al corte el resumen dice $300 y mínimo $25. Si pagás $300 antes del vencimiento, no pagás intereses.',
    impact: 'Pagar solo el mínimo te hace perder el período de gracia: pagás intereses sobre todo el saldo.',
    risks: 'No pagar el mínimo: recargo de $29 y reporte negativo en tu puntaje.',
    tip: 'Activá el débito automático del total si tenés fondos.',
  },
  {
    id: 'periodo_gracia', term: 'Período de gracia', category: 'Crédito y deuda',
    short: 'Tiempo entre el corte y el vencimiento en el que no pagás intereses si abonás el total.',
    purpose: 'Permite usar la tarjeta gratis.',
    example: 'Comprás el 3, el corte es el 25 y vence el 14 del mes siguiente: 41 días sin intereses si pagás todo.',
    impact: 'Se pierde al pagar menos del total y se recupera al volver a pagar el total.',
  },
  {
    id: 'utilizacion_credito', term: 'Utilización de crédito', category: 'Crédito y deuda',
    short: 'Porcentaje de tu límite de tarjeta que estás usando.',
    purpose: 'Es el segundo factor más importante del puntaje crediticio.',
    formula: 'Utilización = Saldo ÷ Límite',
    example: 'Saldo $300 con límite $500 = 60 %: penaliza tu puntaje.',
    impact: 'Por encima del 30 % tu puntaje baja.',
    tip: 'Pagar parte del saldo antes del corte baja la utilización reportada.',
  },
  {
    id: 'puntaje_crediticio', term: 'Puntaje crediticio', category: 'Crédito y deuda',
    short: 'Número de 300 a 850 que resume qué tan confiable sos para prestarte dinero.',
    purpose: 'Define si te aprueban préstamos y a qué tasa (prima de riesgo).',
    formula: 'Historial de pagos (192) + Utilización (165) + Antigüedad (82) + Mezcla (55) + Consultas (55) + 300',
    example: 'Con 700 puntos Banco Austral te cobra +1 pp; con 640 no te presta y Crédito Andino te cobra +6 pp.',
    impact: 'Cada pago a tiempo suma; cada atraso resta durante 24 meses; un impago pesa mucho más.',
    mistakes: 'Pedir muchos préstamos seguidos: cada solicitud registra una consulta que baja el puntaje.',
  },
  {
    id: 'ratio_deuda_ingreso', term: 'Ratio deuda/ingreso', category: 'Crédito y deuda',
    short: 'Qué parte de tu ingreso bruto mensual se va en pagos de deuda.',
    purpose: 'Los bancos lo usan para decidir cuánto prestarte.',
    formula: 'Ratio = Pagos mensuales de deuda ÷ Ingreso bruto mensual',
    example: 'Cuotas $400 con sueldo $1,700 = 23.5 %.',
    impact: 'Banco Austral acepta hasta 36 %, Crédito Andino 43 %, FinaRápido 50 %.',
  },
  {
    id: 'prestamo', term: 'Préstamo personal', category: 'Crédito y deuda',
    short: 'Dinero prestado que devolvés en cuotas fijas con intereses.',
    purpose: 'Financiar algo hoy y pagarlo en el tiempo.',
    formula: 'Cuota = P × r ÷ (1 − (1 + r)^−n), con r = tasa anual ÷ 12',
    example: '$10,000 a 24 meses al 12 %: cuota $470.74; total pagado $11,297.76.',
    impact: 'Las cuotas reducen tu flujo de caja durante todo el plazo. Tres cuotas impagas seguidas = impago y embargo del 20 % del sueldo.',
    risks: 'No aumenta tu patrimonio: sumás dinero y deuda por igual, y la comisión es un gasto inmediato.',
    tip: 'Compará el costo total (intereses + comisión), no solo la cuota.',
  },
  {
    id: 'amortizacion', term: 'Amortización', category: 'Crédito y deuda',
    short: 'La parte de cada cuota que reduce la deuda (el resto son intereses).',
    purpose: 'Muestra cuánto debés realmente después de cada pago.',
    example: 'Primera cuota de $470.74: $100 de interés y $370.74 de amortización.',
    impact: 'Amortizar anticipadamente reduce los intereses futuros sin penalización en este juego.',
    versus: 'En contabilidad de empresas, "amortización" también es el desgaste de intangibles (Fase 2).',
  },
  {
    id: 'comision', term: 'Comisión', category: 'Crédito y deuda',
    short: 'Cargo fijo o porcentual que cobra un banco por un servicio.',
    purpose: 'Es parte del costo real de un producto financiero.',
    example: 'Mantenimiento de cuenta corriente: $4/mes si tu saldo promedio es menor a $1,000. Comisión de apertura de préstamo: 1–5 %.',
    impact: 'Se registra como gasto financiero.',
  },
  {
    id: 'mora', term: 'Mora y atrasos', category: 'Crédito y deuda',
    short: 'Deuda vencida que no pagaste a tiempo.',
    purpose: 'Refleja que no pudiste cumplir una obligación.',
    example: 'Alquiler de $450 sin fondos → atraso de $450 + recargo de $22.50.',
    impact: 'Bloquea créditos, aumenta el estrés y, con dos alquileres atrasados, provoca desalojo.',
  },
  // AHORRO E INVERSIÓN
  {
    id: 'efectivo', term: 'Efectivo', category: 'Ahorro e inversión',
    short: 'Dinero físico en tu billetera.',
    purpose: 'Pagos inmediatos. Es líquido pero no genera intereses.',
    example: 'Retirás $100 de la cuenta corriente al efectivo.',
    impact: 'Es la última fuente de pago antes de la tarjeta si la cuenta corriente no alcanza.',
  },
  {
    id: 'cuenta_corriente', term: 'Cuenta corriente', category: 'Ahorro e inversión',
    short: 'Cuenta para cobrar el sueldo y pagar gastos.',
    purpose: 'Es por donde entra y sale tu dinero del día a día.',
    example: 'Cobrás $976 y se debitan alquiler, servicios y cuotas.',
    impact: 'No paga intereses y cobra $4/mes de mantenimiento si el saldo promedio es menor a $1,000.',
  },
  {
    id: 'cuenta_ahorro', term: 'Cuenta de ahorro', category: 'Ahorro e inversión',
    short: 'Cuenta que paga intereses sobre tu saldo promedio diario.',
    purpose: 'Guardar tu fondo de emergencia sin perder disponibilidad.',
    formula: 'Interés mensual = Σ saldos diarios × tasa anual ÷ 365',
    example: '$3,000 todo el mes al 3 % anual ≈ $7.40 de interés.',
    impact: 'Con el barrido automático activado cubre faltantes de la cuenta corriente.',
  },
  {
    id: 'deposito_plazo', term: 'Depósito a plazo', category: 'Ahorro e inversión',
    short: 'Dinero que prestás al banco por un plazo fijo a cambio de una tasa mayor.',
    purpose: 'Rinde más que el ahorro a cambio de inmovilizar el dinero.',
    formula: 'Interés = Capital × tasa × días ÷ 365 (se cobra al vencimiento)',
    example: '$2,000 a 12 meses al 4.8 % → $96 al vencer.',
    impact: 'Cancelarlo antes: perdés todos los intereses y pagás 0.5 % de comisión.',
    versus: 'Cuenta de ahorro: tasa menor, disponible siempre.',
  },
  {
    id: 'fondo_emergencia', term: 'Fondo de emergencia', category: 'Ahorro e inversión',
    short: 'Ahorro reservado para imprevistos: 3 a 6 meses de gastos esenciales.',
    purpose: 'Evita endeudarte ante un gasto médico o la pérdida del empleo.',
    formula: 'Meses cubiertos = (Ahorro + depósitos) ÷ gastos esenciales mensuales',
    example: 'Gastos esenciales $830/mes → fondo recomendado entre $2,490 y $4,980.',
    impact: 'Es un criterio de las etapas de progreso.',
  },
  {
    id: 'costo_oportunidad', term: 'Costo de oportunidad', category: 'Ahorro e inversión',
    short: 'Lo que dejás de ganar por elegir una opción en lugar de la mejor alternativa.',
    purpose: 'Ayuda a comparar decisiones más allá del gasto visible.',
    example: 'Dejar $5,000 en la cuenta corriente en vez del ahorro al 3 %: costo de oportunidad ≈ $150/año.',
    impact: 'El asesor detecta dinero ocioso y te muestra este costo.',
  },
  {
    id: 'roi', term: 'Rendimiento sobre la inversión (ROI)', category: 'Ahorro e inversión',
    short: 'Cuánto ganaste en relación a lo que invertiste.',
    purpose: 'Comparar inversiones de distinto tamaño.',
    formula: 'ROI = (Ganancia − Costo) ÷ Costo',
    example: 'Un curso de $150 que te permite ganar $200 más al mes rinde 1,500 % en un año.',
    impact: 'La educación también tiene ROI: aumenta tus ingresos futuros.',
  },
  {
    id: 'inflacion', term: 'Inflación', category: 'Ahorro e inversión',
    short: 'Aumento general de los precios. Reduce lo que podés comprar con el mismo dinero.',
    purpose: 'Explica por qué un sueldo que no sube te empobrece.',
    example: 'Inflación 3 %: tu alquiler de $450 pasa a $463.50 el próximo año.',
    impact: 'Cada 1 de enero tus gastos se indexan por la inflación del año; los sueldos solo suben en tu evaluación anual.',
    tip: 'Si tu aumento es menor que la inflación, tu salario real bajó.',
  },
  {
    id: 'dividendos', term: 'Dividendos', category: 'Ahorro e inversión',
    short: 'Parte del beneficio que una empresa reparte a sus accionistas.',
    purpose: 'Ingreso pasivo de las inversiones en acciones.',
    formula: 'Dividendo total = Dividendo por acción × Acciones',
    example: '100 acciones con dividendo de $0.50 = $50.',
    impact: 'Tus empresas pueden repartirlos desde ya; las acciones de bolsa llegan en la Fase 3. Una empresa no puede repartir beneficios que no tiene.',
  },
  {
    id: 'depreciacion', term: 'Depreciación', category: 'Estados financieros',
    short: 'Pérdida de valor de un bien por uso o paso del tiempo, registrada como gasto.',
    purpose: 'Repartir el costo de una máquina o vehículo en su vida útil.',
    formula: 'Depreciación lineal anual = (Costo − Valor residual) ÷ Años de vida útil',
    example: 'Máquina de $10,000, vida 5 años, sin residual → $2,000/año.',
    impact: 'Los equipos de tus empresas se deprecian cada mes. Reduce el beneficio pero no es salida de caja.',
  },
  {
    id: 'punto_equilibrio', term: 'Punto de equilibrio', category: 'Estados financieros',
    short: 'Nivel de ventas en el que no ganás ni perdés.',
    purpose: 'Saber cuánto tenés que vender para cubrir costos fijos.',
    formula: 'Unidades de equilibrio = Costos fijos ÷ (Precio − Costo variable unitario)',
    example: 'Fijos $3,000; precio $10; costo $6 → 750 unidades.',
    impact: 'El asesor calcula las ventas de equilibrio de cada empresa con sus costos fijos y su margen bruto.',
  },
  // IMPUESTOS
  {
    id: 'impuesto_progresivo', term: 'Impuesto progresivo', category: 'Impuestos',
    short: 'Impuesto cuya tasa sube por tramos a medida que el ingreso crece.',
    purpose: 'Cada tasa se aplica solo al dinero dentro de su tramo, no a todo tu ingreso.',
    formula: 'Valdoria: 0 % hasta $9,600 · 10 % hasta $24,000 · 20 % hasta $60,000 · 30 % hasta $150,000 · 37 % el resto',
    example: 'Ingreso $30,000 → 0 + $1,440 + $1,200 = $2,640 (tasa efectiva 8.8 %, marginal 20 %).',
    impact: 'Un aumento nunca te hace ganar menos: solo el dinero extra paga la tasa más alta.',
    mistakes: 'Creer que "pasar de tramo" hace que todo tu ingreso pague más.',
    versus: 'Tasa marginal: la del último dólar. Tasa efectiva: impuesto total ÷ ingreso total.',
  },
  {
    id: 'deduccion', term: 'Deducción fiscal', category: 'Impuestos',
    short: 'Monto que se resta de tu ingreso antes de calcular el impuesto.',
    purpose: 'Reduce la base imponible.',
    formula: 'Ahorro fiscal = Deducción × tu tasa marginal',
    example: 'Aportás $1,000 a jubilación con marginal 20 %: pagás $200 menos de impuesto.',
    impact: 'En Valdoria, los aportes a jubilación son deducibles hasta el 15 % del salario.',
    versus: 'Crédito fiscal: se resta del IMPUESTO, dólar por dólar.',
  },
  {
    id: 'credito_fiscal', term: 'Crédito fiscal', category: 'Impuestos',
    short: 'Monto que se resta directamente del impuesto calculado.',
    purpose: 'Incentivar ciertas conductas (en Valdoria, la educación).',
    formula: 'Crédito educativo = 15 % del gasto en educación, máximo $600/año, no reembolsable',
    example: 'Gastaste $1,000 en cursos: tu impuesto baja $150.',
    impact: 'No reembolsable: si tu impuesto es $0, el crédito no te genera dinero.',
    versus: 'Deducción: reduce la base, su valor depende de tu tasa marginal.',
  },
  {
    id: 'retencion', term: 'Retención', category: 'Impuestos',
    short: 'Impuesto que tu empleador descuenta de cada sueldo y paga por vos por adelantado.',
    purpose: 'Evita que tengas que pagar todo el impuesto de golpe.',
    example: 'Sueldo $2,000: se retienen $110 de impuesto cada mes.',
    impact: 'En la declaración anual se compara lo retenido con el impuesto real: si sobra te devuelven, si falta pagás.',
  },
  {
    id: 'declaracion_fiscal', term: 'Declaración fiscal anual', category: 'Impuestos',
    short: 'Cálculo anual de tu impuesto real, comparado con lo retenido.',
    purpose: 'Liquidar diferencias: intereses sin retención, bonos, deducciones, créditos.',
    formula: 'Saldo = Impuesto − Créditos − Retenciones',
    example: 'Impuesto $1,500, retenido $1,320 → debés $180 antes del 30 de abril.',
    impact: 'Se presenta sola el 31 de diciembre. Pagar tarde: multa 5 % + 1 % mensual.',
  },
  {
    id: 'seguridad_social', term: 'Seguridad social', category: 'Impuestos',
    short: 'Contribución obligatoria del 7 % del sueldo (con tope) para salud pública y pensiones.',
    purpose: 'Financia el sistema público.',
    example: 'Sueldo $2,000 → $140 de seguridad social.',
    impact: 'Es un gasto: no es deducible ni recuperable.',
  },
  {
    id: 'jubilacion', term: 'Fondo de jubilación', category: 'Impuestos',
    short: 'Ahorro para el retiro que se descuenta de tu sueldo; algunos empleadores aportan también.',
    purpose: 'Ahorro de largo plazo con beneficio fiscal.',
    example: 'Aportás 5 % de $2,000 = $100; tu empleador aporta 3 % = $60 extra que es ingreso para vos.',
    impact: 'Es un activo, suma a tu patrimonio, pero NO es liquidez: no podés usarlo para pagar gastos.',
    tip: 'Aportar al menos lo que iguala tu empleador es dinero gratis.',
  },
  // EMPLEO
  {
    id: 'salario_bruto', term: 'Salario bruto', category: 'Empleo',
    short: 'Lo que tu empleador acuerda pagarte antes de descuentos.',
    purpose: 'Es la cifra de las ofertas de empleo y la que usan los bancos.',
    example: 'Oferta de $1,700 brutos.',
    impact: 'Tu estado de resultados muestra el bruto como ingreso y los descuentos como gastos o aportes.',
    versus: 'Salario neto: lo que llega a tu cuenta.',
  },
  {
    id: 'salario_neto', term: 'Salario neto', category: 'Empleo',
    short: 'Lo que efectivamente cobrás después de impuestos, seguridad social y aportes.',
    purpose: 'Es con lo que realmente pagás tus gastos.',
    formula: 'Neto = Bruto − Jubilación − Seguridad social − Retención',
    example: 'Bruto $2,000 − $100 − $140 − $110 = $1,650 netos.',
    impact: 'Planificá tu presupuesto con el neto, no con el bruto.',
  },
  {
    id: 'desempeno', term: 'Desempeño laboral', category: 'Empleo',
    short: 'Puntaje de 0 a 100 que refleja qué tan bien hacés tu trabajo.',
    purpose: 'Define aumentos, bonos, comisiones, ascensos y el riesgo de despido.',
    formula: '50 + habilidades clave vs. exigidas + experiencia + disciplina − estrés alto − salud baja − sobrecarga',
    example: 'Desempeño 72 en la evaluación anual → aumento 4 % y posible ascenso.',
    impact: 'Tres meses seguidos bajo 30 terminan en despido.',
  },
  {
    id: 'habilidades', term: 'Habilidades y experiencia (XP)', category: 'Empleo',
    short: 'Tus conocimientos suben de nivel (1–100) solo con estudio, trabajo y práctica.',
    purpose: 'Abren empleos, mejoran negociaciones y desempeño.',
    formula: 'XP para el siguiente nivel = 20 × nivel^1.35',
    example: 'Pasar del nivel 1 al 10 requiere ~1,700 XP: un libro da 1,200.',
    impact: 'Practicar lo mismo varias veces el mismo día rinde 100 %, 50 %, 25 % y luego nada.',
  },
  // BIENESTAR
  {
    id: 'estres', term: 'Estrés', category: 'Bienestar',
    short: 'Presión acumulada por trabajo, estudio, deudas y estilo de vida.',
    purpose: 'Afecta desempeño y salud.',
    example: 'Trabajar 45 h + estudiar 20 h/semana con estilo austero puede llevarte a 70+.',
    impact: 'Sobre 60 baja tu desempeño; sobre 50 tu salud empieza a caer.',
  },
  {
    id: 'seguro', term: 'Seguro médico', category: 'Bienestar',
    short: 'Cobertura que reduce el costo de un problema de salud a un copago.',
    purpose: 'Transferir un riesgo grande a cambio de un costo fijo.',
    example: 'Sin seguro: $300–$2,500 por imprevisto. Con seguro: $40–$150.',
    impact: 'Muchos empleos lo incluyen. Si no, podés contratar uno privado.',
  },
  {
    id: 'presupuesto', term: 'Presupuesto', category: 'Básicos',
    short: 'Plan de cuánto vas a gastar en cada categoría por mes.',
    purpose: 'Controlar que los gastos no superen tus ingresos.',
    example: 'Neto $1,650 − gastos fijos $890 = $760 para ahorro e imprevistos.',
    impact: 'Tu estilo de vida define los gastos fijos del presupuesto.',
  },
  {
    id: 'asesor', term: 'Asesor', category: 'Acciones del juego',
    short: 'Analiza tu partida y te avisa de riesgos y oportunidades con cálculos verificables.',
    purpose: 'Te ayuda a decidir; nunca actúa por vos.',
    example: '"Te quedarías sin efectivo en 2.3 meses (entre 2.0 y 2.6)".',
    impact: 'Cada alerta separa hechos, estimaciones y opciones con sus riesgos.',
  },
  // ACCIONES DEL JUEGO
  {
    id: 'accion_transferir', term: 'Botón Transferir', category: 'Acciones del juego',
    short: 'Mueve dinero entre tus cuentas propias (efectivo, corriente, ahorro).',
    purpose: 'Ubicar el dinero donde sea más útil: pagar gastos o ganar intereses.',
    example: 'Pasar $500 de la corriente al ahorro.',
    impact: 'No cambia tu patrimonio: es el mismo dinero en otro lugar.',
    risks: 'Dejar la cuenta corriente sin fondos puede hacer fallar un pago (salvo con barrido automático).',
  },
  {
    id: 'accion_barrido', term: 'Barrido automático', category: 'Acciones del juego',
    short: 'Si la cuenta corriente no alcanza para un pago, se transfiere lo que falta desde el ahorro.',
    purpose: 'Evitar atrasos por descuido.',
    example: 'Corriente $300, alquiler $450 → se mueven $150 del ahorro.',
    impact: 'Protege tu puntaje, pero puede consumir tu fondo de emergencia sin que lo notes.',
  },
  {
    id: 'accion_velocidad', term: 'Control del tiempo', category: 'Acciones del juego',
    short: 'Pausa, 1×, 2×, 4× y 8× la velocidad del calendario, o saltos de día, semana y mes.',
    purpose: 'Jugar a tu ritmo: el tiempo del juego es independiente del real.',
    example: '1× = 1 día cada 2 segundos; 8× = 4 días por segundo.',
    impact: 'Todos los calendarios (sueldos, alquileres, cuotas, impuestos) se procesan igual a cualquier velocidad.',
  },
  {
    id: 'accion_postular', term: 'Botón Postularme', category: 'Acciones del juego',
    short: 'Envía tu candidatura a un empleo cuyos requisitos cumplís.',
    purpose: 'Conseguir ingresos o un mejor puesto.',
    example: 'Probabilidad 42 %: responden en 3–10 días.',
    impact: 'Si te ofrecen el puesto tenés 7 días para aceptar, negociar o rechazar.',
    risks: 'Un rechazo impide volver a postularte al mismo puesto durante 30 días.',
  },
  {
    id: 'accion_negociar', term: 'Negociar', category: 'Acciones del juego',
    short: 'Pedir mejores condiciones (salario o tasa).',
    purpose: 'Aumentar tus ingresos o reducir el costo de una deuda.',
    example: 'Pedir +10 % sobre $1,700 con Negociación nivel 10: ~36 % de éxito.',
    impact: 'Pedir mucho aumenta el riesgo: con +15 % o más, la empresa puede retirar la oferta.',
  },
  {
    id: 'accion_estilo', term: 'Cambiar estilo de vida', category: 'Acciones del juego',
    short: 'Mudarte y ajustar tus gastos fijos.',
    purpose: 'Equilibrar comodidad, estrés y ahorro.',
    example: 'De Modesto ($890/mes) a Austero ($585/mes): ahorrás $305/mes pero sumás estrés.',
    impact: 'La mudanza cuesta medio mes del nuevo alquiler.',
  },
];

export const GLOSSARY: GlossaryEntry[] = [...BASE_GLOSSARY, ...GLOSSARY_BUSINESS, ...GLOSSARY_INVEST, ...GLOSSARY_WORLD, ...GLOSSARY_ACTIONS3, ...GLOSSARY_V11, ...GLOSSARY_V12, ...GLOSSARY_V14];

export const GLOSSARY_BY_ID: Record<string, GlossaryEntry> = Object.fromEntries(GLOSSARY.map((g) => [g.id, g]));
