import type { GlossaryEntry } from './glossary';

/** Versión 1.4: la historia del magnate (fortunas, metas, dilemas, crónica, desafíos, rivales con memoria). */
export const GLOSSARY_V14: GlossaryEntry[] = [
  { id: 'ranking_fortunas', term: 'Lista de fortunas', category: 'Mercado y competencia',
    short: 'Las 100 personas más ricas de cada ciudad y un ranking global con las cuatro ciudades juntas.',
    purpose: 'Medir tu fortuna contra la del mundo del juego, no solo contra tu pasado.',
    how: 'Cada persona tiene un origen (tecnología, finanzas, inmuebles, industria, comercio, energía, salud o herencia) y su fortuna sigue al mercado de TU partida cada mes: la bolsa de su sector, el índice inmobiliario de su ciudad y las tasas, más su propia suerte y sus gastos. Los dueños de los grupos rivales están en la lista, y su fortuna incluye el grupo. Tu ciudad es la de tu residencia fiscal. Fuera del top 100 se estima tu puesto con la misma curva de la ciudad.',
    example: 'En Valdoria el puesto 100 arranca cerca de $4 M y el número 1 en unos $3,200 M. Si la bolsa tecnológica sube 20 % en un año, las fortunas tecnológicas suben más que las demás.',
    impact: 'Entrar en la lista, llegar al top 10 o al número 1 da logros, noticias y entradas en tu crónica. Siendo el número 1, quien está segundo puede lanzar una ofensiva.',
    tip: 'Mudar tu residencia a una ciudad con fortunas más chicas (Puerto Nuevo) te hace entrar antes en su lista, pero cambia tus impuestos y tu costo de vida.' },
  { id: 'metas_vida', term: 'Metas de vida', category: 'Acciones del juego',
    short: 'Objetivos que elegís vos (hasta 3 a la vez): tu casa, la cima de tu carrera, una fortuna limpia, superar a un rival…',
    purpose: 'Que tu partida tenga un rumbo propio, no solo acumular dinero.',
    how: 'Se cumplen por el estado real de la partida (no con un botón). Al cumplir una, sumás 3 de reputación, queda en tu crónica y podés elegir otra. Algunas pueden volverse imposibles (por ejemplo, «Una fortuna limpia» si cometiste un acto ilegal).',
    example: '«Independencia financiera» se cumple cuando tus ingresos pasivos cubren todos tus gastos fijos.',
    impact: 'Reputación, logros y una historia que se puede contar.' },
  { id: 'dilemas', term: 'Decisiones con plazo', category: 'Acciones del juego',
    short: 'Situaciones con 2 o 3 opciones que vencen en una fecha: un empleado que pide aumento, un amigo que busca inversores, un ascenso con mudanza…',
    purpose: 'Que tus decisiones tengan consecuencias que se sienten.',
    how: 'Cada opción dice qué cuesta y qué podés ganar. Todo pasa por el libro mayor, los empleados, la carrera y los rivales que ya existen. Si no decidís, se aplica la opción por defecto (que nunca cuesta dinero, pero tiene sus consecuencias). Algunas tienen un desenlace meses después. Pausan el tiempo si lo tenés activado en Ajustes.',
    example: 'Invertir $5,000 en la startup de un amigo se registra como gasto hoy; en uno o dos años puede volver multiplicado, en parte o nada.',
    impact: 'Dinero, reputación, contactos, estrés, moral de tus empleados y la actitud de los rivales.' },
  { id: 'cronica_magnate', term: 'Crónica del magnate', category: 'Acciones del juego',
    short: 'La historia de tu partida como línea de tiempo: etapas, logros, metas, decisiones, crisis y la competencia por la riqueza.',
    purpose: 'Recordar y contar lo que pasó en tu partida.',
    how: 'Se escribe sola. Cada 31 de diciembre agrega un resumen del año con tu patrimonio y tu puesto en la lista. Podés compartirla como texto.',
    example: '«2031 · Superaste a la Familia Duarte». «Tu 2034: patrimonio $1.2 M, creció 18 %».',
    impact: 'Ninguno en la economía: es tu historia.' },
  { id: 'desafios_semilla', term: 'Desafíos con semilla', category: 'Acciones del juego',
    short: 'Escenarios fijos: todos los que juegan un desafío empiezan en el mismo mundo (misma bolsa, mismos empleos, mismas crisis).',
    purpose: 'Comparar tu resultado con el de otras personas de forma justa, sin servidor.',
    how: 'Al cumplir el objetivo recibís un código (por ejemplo MILLON-3650-AB12CD) que incluye el resultado y una verificación contra errores de copia. Se puede comprobar en Más → Desafíos. Si se pasa el plazo, la partida sigue normalmente.',
    example: '«El primer millón»: empezás como autodidacta con $1,500; gana quien llega al millón en menos días.',
    impact: 'Rejugabilidad y maestría: el mismo mundo, otras decisiones.' },
  { id: 'rencor_rivales', term: 'Memoria de los rivales', category: 'Mercado y competencia',
    short: 'Los grupos rivales recuerdan lo que les hacés: si les ganás una compra, los superás en la lista o competís en sus sectores con varias empresas.',
    purpose: 'Que la competencia tenga caras y consecuencias.',
    how: 'Cada grupo tiene un rencor de 0 a 100 que baja solo con el tiempo. Cuanto más alto, más probable que abran competidores, cierren exclusividades con tus proveedores o tienten a tus empleados (hasta el doble). Pueden proponerte una tregua: dos años sin atacarte si no abrís empresas nuevas en un sector. Romperla tiene un costo alto.',
    example: 'Comprás la empresa que Grupo Altamira negociaba: su rencor sube 12 y aparece en su ficha.',
    impact: 'Más o menos ataques en tus sectores.' },
];
