import type { GlossaryEntry } from './glossary';

/** Términos de empresas (Fase 2) y ayuda de cada acción del juego. */
export const GLOSSARY_BUSINESS: GlossaryEntry[] = [
  {
    id: 'forma_legal', term: 'Forma legal de la empresa', category: 'Empresas',
    short: 'El tipo de sociedad define quién responde por las deudas, cómo tributa y qué puede hacer la empresa.',
    purpose: 'Elegir el equilibrio entre costo, riesgo personal e impuestos.',
    example: 'Empresa individual: trámite de $50, sin impuesto empresarial, pero si quiebra pagás sus deudas. SRL: $400 y 25 % de impuesto, pero solo perdés lo aportado.',
    impact: 'Cambia la quiebra, los impuestos, los dividendos y si podés vender acciones.',
    versus: 'Responsabilidad limitada: el riesgo termina en lo aportado. Ilimitada: responde tu patrimonio personal.',
  },
  {
    id: 'responsabilidad_limitada', term: 'Responsabilidad limitada', category: 'Empresas',
    short: 'Si la empresa quiebra, los acreedores cobran solo con los bienes de la empresa, no con los tuyos.',
    purpose: 'Separar el riesgo del negocio de tu patrimonio personal.',
    example: 'Una SRL debe $8,000 y sus activos valen $5,000: los acreedores pierden $3,000; vos perdés lo que aportaste.',
    impact: 'Excepción: los préstamos que garantizaste personalmente los pagás igual.',
  },
  {
    id: 'metodo_participacion', term: 'Método de participación', category: 'Empresas',
    short: 'Tu inversión en una empresa vale tu porcentaje de su patrimonio contable (más la plusvalía pagada).',
    purpose: 'Que tu patrimonio personal refleje las ganancias y pérdidas de tus empresas.',
    formula: 'Valor contable = Patrimonio de la empresa × tu participación + plusvalía',
    example: 'Tenés el 60 % de una empresa con patrimonio $50,000: tu inversión vale $30,000. Si gana $5,000, tu patrimonio sube $3,000.',
    impact: 'Se actualiza cada cierre de mes. Cobrar dividendos no aumenta tu patrimonio: pasa valor de la empresa a tu cuenta.',
    versus: 'Valoración de mercado: lo que pagaría un comprador, que puede ser mayor o menor.',
  },
  {
    id: 'capital_aportado', term: 'Capital aportado', category: 'Empresas',
    short: 'Dinero que los dueños ponen en la empresa. No es un gasto ni un préstamo.',
    purpose: 'Financiar la instalación y los primeros meses.',
    example: 'Aportás $25,000: la caja de la empresa sube $25,000 y tu cuenta personal baja lo mismo; tu patrimonio no cambia.',
    impact: 'Se recupera vía dividendos, venta o liquidación, si el negocio lo permite.',
  },
  {
    id: 'costo_ventas', term: 'Costo de ventas', category: 'Empresas',
    short: 'Lo que costaron directamente las unidades vendidas: insumos, mermas y costos variables.',
    purpose: 'Calcular el beneficio bruto y el margen.',
    formula: 'Beneficio bruto = Ventas − Costo de ventas',
    example: 'Vendés 100 almuerzos a $9.50 con insumos de $3.45: costo de ventas $345, beneficio bruto $605.',
    impact: 'El inventario se valora por FIFO: primero sale lo que entró primero.',
  },
  {
    id: 'ebitda', term: 'EBITDA', category: 'Empresas',
    short: 'Beneficio antes de intereses, impuestos, depreciación y amortización.',
    purpose: 'Medir cuánto genera la operación sin importar cómo se financia ni cuánto se deprecia.',
    formula: 'EBITDA = Beneficio bruto − Gastos operativos',
    example: 'Beneficio bruto $12,000 − gastos operativos $9,000 = EBITDA $3,000.',
    impact: 'Los bancos lo usan para prestar y los compradores para valorar.',
  },
  {
    id: 'valoracion', term: 'Valoración de empresas', category: 'Empresas',
    short: 'Estimación de cuánto vale una empresa.',
    purpose: 'Decidir precios de compra, venta o emisión de acciones.',
    formula: 'Mayor entre: EBITDA anual × múltiplo del sector + caja − deudas, o valor de liquidación de activos − deudas',
    example: 'EBITDA $40,000 × 3 + caja $10,000 − deudas $15,000 = $115,000.',
    impact: 'Con pocos meses de datos, la estimación es poco confiable.',
    risks: 'Un comprador puede ofrecer más o menos que la valoración.',
  },
  {
    id: 'plusvalia', term: 'Plusvalía (goodwill)', category: 'Empresas',
    short: 'Diferencia entre el precio pagado por una empresa y su patrimonio contable.',
    purpose: 'Reflejar que pagaste por clientes, marca y capacidad de generar ganancias.',
    example: 'Pagás $80,000 por una empresa con patrimonio $50,000: plusvalía $30,000.',
    impact: 'Se pierde si la empresa quiebra o se cierra.',
  },
  {
    id: 'cuentas_por_cobrar', term: 'Cuentas por cobrar', category: 'Empresas',
    short: 'Ventas ya realizadas que los clientes pagarán más adelante.',
    purpose: 'Vender a empresas que exigen plazo de pago.',
    example: 'Facturás $5,000 hoy a 30 días: es ingreso hoy, pero la caja entra en un mes.',
    impact: 'Consumen capital de trabajo; un 1.5 % puede terminar incobrable (menos con un contador).',
  },
  {
    id: 'cuentas_por_pagar', term: 'Cuentas por pagar', category: 'Empresas',
    short: 'Compras a proveedores que se pagan más adelante.',
    purpose: 'Financiar el inventario con el crédito del proveedor.',
    example: 'Recibís $3,000 de mercadería a 30 días: la podés vender antes de pagarla.',
    impact: 'Si no pagás al vencimiento: recargo del 3 %, deuda vencida y el proveedor deja de darte crédito.',
  },
  {
    id: 'inventario', term: 'Inventario', category: 'Empresas',
    short: 'Insumos y productos que la empresa tiene para usar o vender. Es un activo, no un gasto, hasta que se vende.',
    purpose: 'Evitar faltantes sin inmovilizar demasiado dinero.',
    formula: 'Días de cobertura = Existencias ÷ Consumo diario',
    example: '300 kg con un consumo de 20 kg/día = 15 días de cobertura.',
    impact: 'Demasiado: capital inmovilizado, almacenamiento y vencimientos. Poco: ventas perdidas.',
  },
  {
    id: 'punto_reorden', term: 'Punto de pedido y stock de seguridad', category: 'Empresas',
    short: 'Nivel de existencias en el que conviene volver a pedir para no quedarse sin stock mientras llega el pedido.',
    purpose: 'Automatizar la reposición.',
    formula: 'Stock de seguridad = Consumo × Plazo × 0.5 · Punto de pedido = Consumo × Plazo + Stock de seguridad',
    example: 'Consumo 10/día, plazo 3 días: seguridad 15, punto de pedido 45.',
    impact: 'Las reglas de reposición piden solas cuando existencias + en tránsito ≤ punto de pedido.',
  },
  {
    id: 'mermas', term: 'Mermas', category: 'Empresas',
    short: 'Pérdidas de inventario por vencimiento, robo o errores.',
    purpose: 'Medir cuánto se pierde antes de vender.',
    example: 'Compraste 200 panes que duran 3 días y vendiste 120: 80 se descartan.',
    impact: 'Se registran como costo de ventas. La refrigeración, las cámaras y un contador las reducen.',
  },
  {
    id: 'nomina', term: 'Nómina y cargas sociales', category: 'Empresas',
    short: 'Sueldos del personal más el 12 % de cargas del empleador (seguridad social y prestaciones).',
    purpose: 'Conocer el costo laboral real.',
    formula: 'Costo laboral = Sueldo × 1.12',
    example: '4 empleados de $1,000 cuestan $4,480 por mes.',
    impact: 'Se paga el último día del mes. Si no se paga, la moral cae y renuncian.',
  },
  {
    id: 'capacidad', term: 'Capacidad operativa', category: 'Empresas',
    short: 'Cuánto puede producir o atender la empresa por día según su personal y equipos.',
    purpose: 'Saber si podés atender toda la demanda.',
    example: '2 cocineros × 60 unidades de trabajo = 120; un almuerzo usa 1.5.',
    impact: 'Sin capacidad suficiente se pierden ventas; con capacidad ociosa se paga de más.',
  },
  {
    id: 'cuota_mercado', term: 'Cuota de mercado', category: 'Empresas',
    short: 'Qué parte de la demanda total del sector compra en tu empresa.',
    purpose: 'Compararte con la competencia.',
    formula: 'Atractivo = f(precio, calidad, reputación, conocimiento de marca) · Cuota = tu atractivo ÷ (total + no comprar)',
    example: 'El mercado pide 1,000 cafés/día y vendés 80: cuota 8 %.',
    impact: 'Si superás el 20 %, los competidores tienden a bajar precios.',
  },
  {
    id: 'elasticidad', term: 'Elasticidad precio', category: 'Empresas',
    short: 'Cuánto cambia la demanda cuando cambia el precio.',
    purpose: 'Decidir precios.',
    example: 'Con elasticidad 3 (minimercado), subir 10 % el precio reduce mucho las ventas; con 1 (consultora), poco.',
    impact: 'Cada sector tiene su propia elasticidad.',
  },
  {
    id: 'conocimiento_marca', term: 'Conocimiento de marca', category: 'Empresas',
    short: 'Qué porcentaje del mercado conoce tu empresa (0–100).',
    purpose: 'Sin conocimiento no hay clientes, aunque el producto sea bueno.',
    example: 'Una empresa nueva empieza con 10. Sin marketing tiende a quedarse baja.',
    impact: 'Se olvida un 1 % por día; el marketing lo sube con rendimientos decrecientes (saturación).',
  },
  {
    id: 'marketing', term: 'Campañas de marketing', category: 'Empresas',
    short: 'Gasto diario en un canal para aumentar el conocimiento, la reputación o el atractivo.',
    purpose: 'Conseguir clientes.',
    example: 'Publicidad digital $50/día durante 60 días.',
    impact: 'No vende por sí sola: la demanda también depende de precio, calidad, reputación y stock.',
    risks: 'Saturación: cuanto más te conocen, menos rinde cada dólar. Redes sociales con mala calidad pueden dañar la reputación.',
  },
  {
    id: 'impuesto_empresarial', term: 'Impuesto empresarial', category: 'Empresas',
    short: 'SRL y corporaciones pagan 25 % sobre su beneficio anual; empresas individuales y sociedades no pagan: su resultado va a tu declaración.',
    purpose: 'Planificar el costo fiscal según la forma legal.',
    formula: 'Impuesto = 25 % × (Beneficio − pérdidas de hasta 5 años anteriores)',
    example: 'Beneficio $40,000 con $10,000 de pérdidas previas: impuesto $7,500.',
    impact: 'Se calcula el 1 de enero y vence el 30 de abril. Los dividendos pagan 10 % adicional.',
  },
  {
    id: 'quiebra', term: 'Insolvencia y quiebra', category: 'Empresas',
    short: 'Insolvencia: la empresa no puede pagar deudas vencidas. Quiebra: se liquida por no regularizarlas a tiempo.',
    purpose: 'Un proceso claro con advertencias antes de perder la empresa.',
    example: 'Deudas vencidas → 60 días para regularizar → venta forzada de activos (inventario al 30 %, equipos al 40 %).',
    impact: 'Con responsabilidad limitada perdés lo invertido; con ilimitada pagás lo que falte con tu dinero.',
  },
  {
    id: 'ganancia_capital', term: 'Ganancia de capital', category: 'Impuestos',
    short: 'La diferencia positiva entre el precio de venta de un activo y su valor contable.',
    purpose: 'Calcular el impuesto al vender una empresa.',
    formula: 'Impuesto = 15 % × (Precio − comisión − valor contable)',
    example: 'Vendés en $100,000 una empresa que en tus libros vale $70,000: ganancia $27,000 tras la comisión; impuesto $4,050.',
    impact: 'Si vendés con pérdida, no hay impuesto.',
  },
  {
    id: 'costo_adquisicion', term: 'Costos de adquisición', category: 'Empresas',
    short: 'Gastos legales, de auditoría y de intermediación al comprar o vender una empresa.',
    purpose: 'Incluirlos en el costo real de la operación.',
    example: 'Comprar por $60,000 cuesta $1,800 más (3 %).',
    impact: 'Son gasto inmediato: reducen tu patrimonio.',
  },
  {
    id: 'diversificacion', term: 'Diversificación', category: 'Ahorro e inversión',
    short: 'Repartir el patrimonio entre distintos activos para no depender de uno solo.',
    purpose: 'Reducir el riesgo total.',
    example: 'Tener empresa, fondo de emergencia y depósitos, en lugar de todo en la empresa.',
    impact: 'El asesor avisa si más del 75 % de tus activos está en tus empresas.',
  },
  {
    id: 'delegacion', term: 'Delegación en un gerente', category: 'Empresas',
    short: 'Un gerente general puede encargarse de la reposición, los precios y el personal.',
    purpose: 'Ahorrarte trabajo manual cuando tenés varias empresas.',
    example: 'Un gerente de habilidad 70 ajusta cada semana cantidades y precios con pocos errores.',
    impact: 'Cuesta un sueldo alto; un gerente de habilidad baja se equivoca más en las cantidades.',
  },
  {
    id: 'dividendos_empresa', term: 'Dividendos y retiros', category: 'Empresas',
    short: 'Pasar dinero de la caja de la empresa a tu cuenta personal.',
    purpose: 'Cobrar los frutos del negocio.',
    example: 'SRL con $20,000 de beneficio acumulado: podés repartir hasta ese monto (si la caja lo permite) y te retienen 10 %.',
    impact: 'Reduce la caja y el patrimonio de la empresa. Se deja una reserva para gastos fijos.',
    versus: 'En empresas individuales se llaman retiros y no pagan el 10 % (ya tributaron en tu declaración).',
  },
  // ---- Acciones de empresas
  { id: 'accion_fundar', term: 'Fundar empresa', category: 'Acciones del juego', short: 'Crea una empresa con tu capital: paga trámites, licencia, depósito, equipos y personal inicial.', purpose: 'Empezar un negocio desde cero.', example: 'Minimercado individual: instalación ≈ $13,000; conviene aportar al menos $22,000 para sostener los primeros meses.', impact: 'Tu dinero pasa a "Participaciones en empresas". Abre al público 7 días después.', risks: 'Con poco capital de trabajo la empresa puede quedarse sin caja y quebrar.' },
  { id: 'accion_comprar_empresa', term: 'Comprar empresa', category: 'Acciones del juego', short: 'Adquiere una empresa en marcha con clientes, personal, inventario e historia.', purpose: 'Saltarse el arranque.', example: 'Pedido $70,000; podés contraofertar una vez.', impact: 'Pagás el precio más 3 % de costos. La diferencia con su patrimonio es plusvalía.', risks: 'Pagar más de lo que vale; heredar problemas (deudas, moral baja).' },
  { id: 'accion_aportar', term: 'Aportar capital', category: 'Acciones del juego', short: 'Pasa dinero de tu cuenta a la caja de la empresa.', purpose: 'Financiar crecimiento o salir de la insolvencia.', example: 'Aportar $5,000 cuando hay deudas vencidas las paga de inmediato.', impact: 'Tu patrimonio no cambia; tu liquidez personal baja.' },
  { id: 'accion_dividendos', term: 'Repartir dividendos / retirar', category: 'Acciones del juego', short: 'Pasa dinero de la empresa a tu cuenta corriente.', purpose: 'Cobrar lo que genera el negocio.', example: 'Límite: caja menos reserva, y en SRL/corporación solo beneficios acumulados.', impact: 'Liquidez personal ↑, caja de la empresa ↓.' },
  { id: 'accion_vender_empresa', term: 'Vender empresa', category: 'Acciones del juego', short: 'Pide una oferta a compradores y, si la aceptás, cobrás el precio menos comisión e impuestos.', purpose: 'Realizar la ganancia de lo construido.', example: 'Oferta $90,000 por una empresa valorada en $95,000.', impact: 'Se cobra 3 % de comisión y 15 % sobre la ganancia de capital.' },
  { id: 'accion_liquidar', term: 'Cerrar empresa', category: 'Acciones del juego', short: 'Liquidación ordenada: se venden activos, se pagan deudas y el remanente es tuyo.', purpose: 'Salir de un negocio sin llegar a la quiebra.', example: 'Recupera 50 % del inventario y 60 % de los equipos (en quiebra: 30 % y 40 %).', impact: 'Si las deudas superan los activos y la responsabilidad es ilimitada, pagás la diferencia.' },
  { id: 'accion_pedido', term: 'Hacer pedido', category: 'Acciones del juego', short: 'Compra insumos a un proveedor.', purpose: 'Tener stock para producir y vender.', example: '200 kg a $1.30 con entrega en 1 día.', impact: 'Al contado baja la caja al pedir; a crédito se paga al vencimiento. El flete se paga al pedir.', risks: 'Proveedores poco confiables pueden demorarse 1–4 días.' },
  { id: 'accion_regla', term: 'Regla de reposición', category: 'Acciones del juego', short: 'Pide automáticamente cuando las existencias caen al punto de pedido.', purpose: 'No depender de acordarte de comprar.', example: 'Punto 45, cantidad 150: cuando quedan 45 o menos (contando lo en camino), pide 150.', impact: 'Solo pide si hay caja; si no, avisa.' },
  { id: 'accion_contratar', term: 'Contratar', category: 'Acciones del juego', short: 'Suma un empleado: más capacidad o un efecto de su departamento.', purpose: 'Crecer o cubrir un cuello de botella.', example: 'Costo de selección: 25 % del sueldo (la mitad con RR. HH.).', impact: 'Aumenta la nómina mensual.' },
  { id: 'accion_despedir', term: 'Despedir', category: 'Acciones del juego', short: 'Termina el contrato pagando días trabajados e indemnización (mínimo medio sueldo, un sueldo por año).', purpose: 'Ajustar costos.', example: 'Empleado de $1,000 con 2 años: indemnización $2,000.', impact: 'Baja la nómina, pero la moral del resto cae 4 puntos.' },
  { id: 'accion_capacitar', term: 'Capacitar', category: 'Acciones del juego', short: '10 días de curso: +8 de habilidad y +5 de moral; mientras tanto no produce.', purpose: 'Mejorar calidad y productividad.', example: 'Costo $300.', impact: 'Más calidad del producto a largo plazo.' },
  { id: 'accion_salario', term: 'Cambiar salario', category: 'Acciones del juego', short: 'Ajusta el sueldo de un empleado.', purpose: 'Retener talento o bajar costos.', example: 'Pagar por debajo del mercado baja la moral y aumenta las renuncias.', impact: 'Cambia la nómina y la moral de inmediato.' },
  { id: 'accion_campana', term: 'Lanzar campaña', category: 'Acciones del juego', short: 'Programa un gasto diario en un canal de marketing.', purpose: 'Ganar conocimiento de marca y clientes.', example: 'Digital $40/día × 60 días = $2,400.', impact: 'Se paga cada día desde la caja; si no hay caja, se suspende.' },
  { id: 'accion_estudio', term: 'Estudio de mercado', category: 'Acciones del juego', short: 'Informe de 90 días con la demanda del sector, elasticidad y datos exactos de la competencia.', purpose: 'Decidir precios y capacidad con información.', example: 'Cuesta $600.', impact: 'Sin estudio, los datos de rivales se muestran como estimaciones aproximadas.' },
  { id: 'accion_precio', term: 'Cambiar precio', category: 'Acciones del juego', short: 'Define a cuánto vendés cada producto.', purpose: 'Equilibrar margen y volumen.', example: 'Café a $2.80 en vez de $2.50: más margen, menos clientes.', impact: 'Afecta la demanda según la elasticidad del sector.' },
  { id: 'accion_plan', term: 'Plan de producción', category: 'Acciones del juego', short: 'Unidades a fabricar por día de cada producto (manufactura).', purpose: 'Tener stock para vender.', example: 'Plan 5 sillas/día consume 10 tablones y 5 unidades de trabajo.', impact: 'Si el plan supera la capacidad o los insumos, se produce menos.' },
  { id: 'accion_equipo', term: 'Comprar o vender equipos', category: 'Acciones del juego', short: 'Los equipos aumentan la capacidad o la calidad y se deprecian mensualmente.', purpose: 'Crecer sin solo contratar.', example: 'Router CNC: $28,000, +60 % de capacidad, 96 meses de vida.', impact: 'Comprar es inversión (no gasto): el gasto es la depreciación mensual.' },
  { id: 'accion_mantenimiento', term: 'Política de mantenimiento', category: 'Acciones del juego', short: 'Ninguno, básico o preventivo: define el desgaste mensual de los equipos.', purpose: 'Evitar averías.', example: 'Sin mantenimiento la condición baja 5 puntos por mes; bajo 50 aumentan las averías.', impact: 'Costo mensual vs. riesgo de reparaciones y capacidad perdida.' },
  { id: 'accion_prestamo_empresa', term: 'Préstamo empresarial', category: 'Acciones del juego', short: 'Crédito a nombre de la empresa.', purpose: 'Financiar crecimiento o capital de trabajo.', example: 'Banco Austral exige 180 días y EBITDA; Crédito Andino presta a empresas nuevas con tu garantía personal.', impact: 'Si garantizás y la empresa quiebra, pagás vos.' },
  { id: 'accion_emitir', term: 'Vender acciones a inversionistas', category: 'Acciones del juego', short: 'Una corporación vende un porcentaje a inversionistas a cambio de capital.', purpose: 'Crecer sin deuda.', example: 'Vender 20 % con valoración $200,000 ingresa $50,000.', impact: 'Tu participación baja (dilución). No podés bajar de 51 %.' },
  { id: 'accion_delegar', term: 'Delegar', category: 'Acciones del juego', short: 'Permite que el gerente administre reposición, precios y personal.', purpose: 'Reducir trabajo manual.', example: 'Revisa cada semana.', impact: 'Tiene un costo (sueldo del gerente) y sus decisiones pueden no ser óptimas.' },
  // ---- Acciones de la Fase 1
  { id: 'accion_pagar_tarjeta', term: 'Pagar tarjeta', category: 'Acciones del juego', short: 'Paga el saldo de la tarjeta desde la cuenta corriente.', purpose: 'Evitar intereses y mora.', example: 'Pagar el total del resumen antes del vencimiento = cero intereses.', impact: 'Liquidez ↓, deuda ↓; patrimonio igual.' },
  { id: 'accion_debito_automatico', term: 'Débito automático', category: 'Acciones del juego', short: 'Paga la tarjeta sola el día del vencimiento.', purpose: 'No olvidarte nunca.', example: 'Modo "Total": paga todo el resumen si hay fondos.', impact: 'Si no hay fondos suficientes, paga lo que pueda.' },
  { id: 'accion_aumento_limite', term: 'Aumento de límite', category: 'Acciones del juego', short: 'Pide al banco más cupo en la tarjeta.', purpose: 'Bajar la utilización y tener más margen.', example: 'Requiere puntaje 680 e ingreso.', impact: 'Registra una consulta que baja un poco tu puntaje.' },
  { id: 'accion_solicitar_prestamo', term: 'Solicitar préstamo', category: 'Acciones del juego', short: 'Firma un préstamo personal con el banco elegido.', purpose: 'Obtener dinero hoy a cambio de cuotas.', example: 'Recibís el monto menos la comisión.', impact: 'Consulta de crédito, cuotas mensuales e intereses.' },
  { id: 'accion_amortizar', term: 'Amortizar anticipadamente', category: 'Acciones del juego', short: 'Paga capital extra de un préstamo.', purpose: 'Ahorrar intereses futuros.', example: 'Pagar $500 extra reduce la cuota de los meses siguientes.', impact: 'Sin penalización en este juego.' },
  { id: 'accion_abrir_deposito', term: 'Abrir depósito', category: 'Acciones del juego', short: 'Inmoviliza dinero a plazo fijo por una tasa mayor.', purpose: 'Ganar más interés.', example: '$1,000 a 12 meses.', impact: 'Liquidez ↓, inversión ↑.' },
  { id: 'accion_cancelar_deposito', term: 'Cancelar depósito', category: 'Acciones del juego', short: 'Recupera el capital antes del vencimiento.', purpose: 'Liquidez de emergencia.', example: 'Perdés los intereses y pagás 0.5 %.', impact: 'Patrimonio ↓ por la comisión.' },
  { id: 'accion_medio_pago', term: 'Medio de pago de un gasto', category: 'Acciones del juego', short: 'Elige si un gasto recurrente se paga con débito, tarjeta o efectivo.', purpose: 'Organizar tu flujo.', example: 'Supermercado con tarjeta: pagás a fin de mes sin intereses si pagás el total.', impact: 'El alquiler no se puede pagar con tarjeta.' },
  { id: 'accion_pagar_atrasos', term: 'Pagar atrasos', category: 'Acciones del juego', short: 'Cancela pagos vencidos.', purpose: 'Evitar desalojo y recuperar acceso al crédito.', example: '$450 de alquiler atrasado más recargo.', impact: 'Liquidez ↓, deuda ↓.' },
  { id: 'accion_pagar_impuestos', term: 'Pagar impuestos', category: 'Acciones del juego', short: 'Paga el saldo de la declaración anual.', purpose: 'Evitar multas.', example: 'Antes del 30 de abril.', impact: 'Liquidez ↓, deuda fiscal ↓.' },
  { id: 'accion_renunciar', term: 'Renunciar', category: 'Acciones del juego', short: 'Deja tu empleo; cobrás los días trabajados.', purpose: 'Cambiar de rumbo o dedicarte a tus negocios.', example: 'Sin empleo, tus gastos siguen.', impact: 'Perdés el ingreso mensual.' },
  { id: 'accion_oferta', term: 'Aceptar o rechazar oferta', category: 'Acciones del juego', short: 'Decide sobre una oferta de empleo antes de que venza (7 días).', purpose: 'Conseguir ingresos o mejorarlos.', example: 'Aceptar con empleo actual = cambio de trabajo.', impact: 'El sueldo se paga a fin de mes, prorrateado.' },
  { id: 'accion_inscribirse', term: 'Inscribirme', category: 'Acciones del juego', short: 'Comienza un libro, curso, tutoría, certificación o título.', purpose: 'Subir habilidades y abrir empleos.', example: 'Títulos cobran matrícula cada 30 días.', impact: 'Suma horas semanales (estrés) y genera crédito fiscal educativo.' },
  { id: 'accion_abandonar_curso', term: 'Abandonar curso', category: 'Acciones del juego', short: 'Deja un estudio en curso.', purpose: 'Liberar horas o dinero.', example: 'Conservás la XP ganada.', impact: 'Lo pagado no se devuelve.' },
  { id: 'accion_escenarios', term: '¿Qué pasaría si…?', category: 'Acciones del juego', short: 'Simula una copia de tu partida con una decisión hipotética.', purpose: 'Comparar opciones sin riesgo.', example: 'Fundar un minimercado con $14,000 y ver la liquidez a 12 meses.', impact: 'No cambia tu partida real.' },
  { id: 'accion_guardar', term: 'Guardar partida', category: 'Acciones del juego', short: 'Guarda ahora (también se guarda solo cada 30 días de juego y al salir).', purpose: 'No perder progreso.', example: 'En Android se guarda en dos almacenes nativos.', impact: 'Rota copias de seguridad.' },
  { id: 'accion_exportar', term: 'Exportar', category: 'Acciones del juego', short: 'Crea un archivo o texto con tu partida (o tu libro mayor en CSV).', purpose: 'Respaldo externo o pasar la partida a otro dispositivo.', example: 'En Android abre el menú Compartir para guardar en Archivos o Drive.', impact: 'Al importar se verifica la contabilidad.' },
  { id: 'accion_auditar', term: 'Auditar contabilidad', category: 'Acciones del juego', short: 'Recalcula todos los saldos desde los asientos y verifica cada conciliación.', purpose: 'Comprobar que nada se descuadró.', example: '"12,345 asientos verificados: todo cuadra".', impact: 'Solo lectura.' },
  { id: 'accion_restaurar', term: 'Restaurar copia', category: 'Acciones del juego', short: 'Vuelve a una copia de seguridad anterior.', purpose: 'Recuperarte de un error.', example: 'Copias separadas por al menos 30 días de juego.', impact: 'Reemplaza la partida actual.' },
  { id: 'guia_inicio', term: 'Guía de inicio', category: 'Acciones del juego', short: 'Pasos opcionales que se marcan solos cuando los hacés de verdad.', purpose: 'Aprender el juego sin obligaciones.', example: 'Podés omitirla y verla luego en Ajustes.', impact: 'No bloquea nada.' },
  { id: 'nivel_magnate', term: 'Nivel de magnate', category: 'Básicos', short: 'Etapa de 1 a 12 según patrimonio, solvencia, ingresos pasivos y empresas.', purpose: 'Medir tu progreso con varios criterios, no solo dinero.', example: 'Etapa 3 exige un fondo de emergencia de 1 mes y cero atrasos.', impact: 'Nunca retrocede. Ninguna etapa exige una ruta concreta.' },
  { id: 'nivel_profesional', term: 'Nivel profesional', category: 'Empleo', short: 'Sube con meses trabajados, ponderados por nivel del puesto y desempeño.', purpose: 'Reflejar tu trayectoria laboral.', formula: 'Nivel = 1 + √(puntos ÷ 40)', example: 'Un año como asistente con desempeño 50 da 120 puntos.', impact: 'Es informativo; los requisitos reales de los empleos son habilidades, educación y experiencia.' },
  { id: 'probabilidad_oferta', term: 'Probabilidad de oferta', category: 'Empleo', short: 'Chance de que una postulación termine en oferta.', purpose: 'Decidir a cuántos puestos postularte.', formula: '35 % + inteligencia social + reputación + red + habilidades y experiencia extra ± suerte ± tu imagen (hasta ±6 puntos), × el mercado laboral (con mucho desempleo, menos chances) × 0.6 si tenés antecedentes penales. Queda entre 5 % y 92 %.', example: '40 % por puesto: postulando a 3, la chance de al menos una oferta es 78 %.', impact: 'Un rechazo bloquea ese puesto 30 días.' },
];
